// Mağaza, deste sayfası ve Destekle metinleri (TR/EN). Fiyat hiçbir zaman burada yazılmaz (StoreKit
// displayPrice). Ürün adları docs/magaza-taslak.md §5 ile uyumludur. Hepsi kartı yalnız bu sürümde olanı
// sayar: Emoji kipi (haklar.js'te Hepsi'ye dahil, 1.0'da yok) çıktığı sürümde madde olarak eklenir
// (App Store Kılavuzu 2.3.1).

/** "Kitchen (Turkish)" → "Kitchen deck (Turkish)". */
const enDeck = (name) => {
  const m = /^(.*?)(\s*\(.*\))?$/.exec(name);
  return `${m[1]} deck${m[2] || ''}`;
};

export const STORE = {
  tr: {
    storeTitle: 'Mağaza',
    storeIntro: 'Kuran öder, oynayan ödemez: satın aldığın desteyle sen anlatırsın, arkadaşların ücretsiz çözer. Reklam yok.',
    storeRowSub: 'Desteler, kart temaları, Hepsi',
    allTitle: 'Tek seferde hepsi',
    allProduct: (name) => `${name} Hepsi`,
    allBullet1: 'Bugünkü ve gelecekteki bütün desteler',
    allBullet2: 'Günün sözcüğü arşivi: geçmiş günlerin sözcükleriyle anlat',
    allNote: 'Kart temaları ayrıdır.',
    allHint: 'Bütün desteler, gelecekte eklenecekler de, Hepsi paketinde.',
    decksTitle: 'Desteler',
    deckProduct: (name) => `${name} destesi`,
    deckBullet1: (n) => `${n} sözcükle anlatım yaz`,
    deckBullet2: 'Bu desteden gelen anlatımları arkadaşların ücretsiz çözer',
    deckBullet3: 'Bir kez al, hep kullan',
    themesTitle: 'Kart temaları',
    themesProduct: 'Kart temaları',
    themesBullet1: 'Daktilo, Tebeşir, Neon ve Gazete',
    themesBullet2: 'Paylaşılan kart ve oyun ekranları için',
    themesBullet3: 'Oyunda avantaj vermez',
    themePreviewAlt: (name) => `${name} temasında örnek kart`,
    familySharing: 'Aile Paylaşımı ile paylaşılır',
    buyFor: (price) => `Satın al · ${price}`,
    owned: 'Alındı',
    purchaseBusy: 'Ödeme sürüyor…',
    purchaseDone: 'Satın alındı. Teşekkürler!',
    purchasePending: 'Ödeme onay bekliyor (Satın Alma İzni). Onaylanınca kendiliğinden açılır.',
    purchaseFailed: 'Satın alma tamamlanamadı.',
    restorePurchases: 'Satın alımları geri yükle',
    restoreDone: 'Satın alımların geri yüklendi.',
    restoreNothing: 'Geri yüklenecek satın alım bulunamadı.',
    restoreFailed: 'Geri yükleme tamamlanamadı.',
    requestRefund: 'İade iste',
    refundFailed: 'İade sayfası açılamadı.',
    refundRequested: "İade isteğin Apple'a iletildi.",
    openStore: 'Mağazayı aç',
    useDeck: 'Bu desteyle anlat',
    pickFreeDeck: 'Ücretsiz destelere dön',
    creatorPays: 'Kuran öder, oynayan ödemez: bu desteyle sen anlatırsın; arkadaşların gelen anlatımı ücretsiz çözer.',
    sampleWords: 'Örnek sözcükler:',
    purchases: 'Satın alımlar',
    tipsTitle: 'Destekle',
    tipsRow: 'Destekle',
    tipsRowSub: 'Bir çay ısmarla',
    tipIntro: (name) => `${name}'i beğendiysen bir çay ısmarlayabilirsin. Hiçbir şey açmaz; yalnız teşekkürümüzdür.`,
    tipSupporter: 'Desteğin için teşekkürler!',
    tipThanks: () => 'Teşekkürler! Desteğin bize ulaştı.',
    supporter: 'Destekçi',
    tip_cay: 'Bir çay ısmarla',
    tip_kahve: 'Bir kahve ısmarla',
    tip_yemek: 'Bir öğle yemeği ısmarla',
  },
  en: {
    storeTitle: 'Store',
    storeIntro: "The creator pays, the player doesn't: you write with the decks you buy, and friends solve for free. No ads.",
    storeRowSub: 'Decks, card themes, All',
    allTitle: 'Everything at once',
    allProduct: (name) => `${name} All`,
    allBullet1: "Every deck, today's and future ones",
    allBullet2: "Word of the day archive: write with past days' words",
    allNote: 'Card themes are separate.',
    allHint: 'Every deck, including future ones, comes with All.',
    decksTitle: 'Decks',
    deckProduct: (name) => enDeck(name),
    deckBullet1: (n) => `Write clues with ${n} ${n === 1 ? 'word' : 'words'}`,
    deckBullet2: 'Friends solve clues from this deck for free',
    deckBullet3: 'Buy once, keep it',
    themesTitle: 'Card themes',
    themesProduct: 'Card themes',
    themesBullet1: 'Typewriter, Chalk, Neon and Newsprint',
    themesBullet2: 'For the shared card and the game screens',
    themesBullet3: 'No gameplay advantage',
    themePreviewAlt: (name) => `Sample card in the ${name} theme`,
    familySharing: 'Shared with Family Sharing',
    buyFor: (price) => `Buy · ${price}`,
    owned: 'Purchased',
    purchaseBusy: 'Payment in progress…',
    purchaseDone: 'Purchased. Thank you!',
    purchasePending: 'The payment is waiting for approval (Ask to Buy). It unlocks by itself once approved.',
    purchaseFailed: "The purchase couldn't be completed.",
    restorePurchases: 'Restore Purchases',
    restoreDone: 'Your purchases were restored.',
    restoreNothing: 'No purchases to restore.',
    restoreFailed: "Restore couldn't be completed.",
    requestRefund: 'Request a refund',
    refundFailed: "Couldn't open the refund page.",
    refundRequested: 'Your refund request was sent to Apple.',
    openStore: 'Open the store',
    useDeck: 'Write with this deck',
    pickFreeDeck: 'Back to the free decks',
    creatorPays: "The creator pays, the player doesn't: you write with this deck; friends solve your clues for free.",
    sampleWords: 'Sample words:',
    purchases: 'Purchases',
    tipsTitle: 'Support',
    tipsRow: 'Support us',
    tipsRowSub: 'Buy us a tea',
    tipIntro: (name) => `If you enjoy ${name}, you can buy us a tea. It unlocks nothing; it's simply a thank-you.`,
    tipSupporter: 'Thanks for your support!',
    tipThanks: () => 'Thank you! Your support reached us.',
    supporter: 'Supporter',
    tip_cay: 'Buy us a tea',
    tip_kahve: 'Buy us a coffee',
    tip_yemek: 'Buy us lunch',
  },
};
