// Çözme arşivi: ekibin yazdığı anlatımlar (soğuk başlangıç; arkadaşı olmayan oyuncu bunları çözer). Ücretsizdir.
// Biçim: docs/icerik-bicimi.md §6. Yazan: C2 (özgün; başka oyundan ya da kaynaktan alınmadı).
// - Numara kalıcıdır: yayından sonra kayıt silinmez, sırası değişmez; yeni kayıt sona eklenir.
// - Türkçe 1–150, İngilizce 151–200; her dil kendi içinde kolaydan zora (zorluk 1 → 3).
// - Her anlatım kendi kaydının bütün kurallarıyla geçerlidir; hiçbir anlatım başka bir arşiv kaydının cevabını
//   (ya da ekli hâlini) içermez; aynı yasak harf art arda en çok 3 kez gelir (web/tests/icerik-arsiv.test.js).
// - İlk ekran örnekleri: ILK_EKRAN (aşağıda).
export const COZME_ARSIVI = Object.freeze([
  // Türkçe — zorluk 1
  { no: 1, dil: 'tr', deste: 'temel', soz: 'kedi', harf: 'E', anlatim: 'Miyavlayan tüylü dost', zorluk: 1 },
  { no: 2, dil: 'tr', deste: 'temel', soz: 'güneş', harf: 'R', anlatim: 'Gündüz gökyüzündeki sıcak top', zorluk: 1 },
  { no: 3, dil: 'tr', deste: 'temel', soz: 'şemsiye', harf: 'İ', anlatim: 'Yağmurda açılan, rüzgârda ters dönen', zorluk: 1 },
  { no: 4, dil: 'tr', deste: 'temel', soz: 'anahtar', harf: 'R', anlatim: 'Kapıyı açan küçük metal', zorluk: 1 },
  { no: 5, dil: 'tr', deste: 'temel', soz: 'kardan adam', harf: 'İ', anlatim: 'Havuç burunlu soğuk heykel', zorluk: 1 },
  { no: 6, dil: 'tr', deste: 'temel', soz: 'bisiklet', harf: 'O', anlatim: 'İki tekerli pedallı taşıt', zorluk: 1 },
  { no: 7, dil: 'tr', deste: 'temel', soz: 'köpek', harf: 'K', anlatim: 'Postacının en sevmediği havlayan dost', zorluk: 1 },
  { no: 8, dil: 'tr', deste: 'temel', soz: 'penguen', harf: 'E', anlatim: 'Smokinli, uçamayan kutup kuşu', zorluk: 1 },
  { no: 9, dil: 'tr', deste: 'temel', soz: 'kaplumbağa', harf: 'A', anlatim: 'Evini sırtı üstünde götüren sürüngen', zorluk: 1 },
  { no: 10, dil: 'tr', deste: 'temel', soz: 'zürafa', harf: 'A', anlatim: 'Boyu ve boynu en uzun benekli', zorluk: 1 },
  { no: 11, dil: 'tr', deste: 'temel', soz: 'fil', harf: 'L', anlatim: 'Hortumu var, kocaman, gri', zorluk: 1 },
  { no: 12, dil: 'tr', deste: 'temel', soz: 'örümcek', harf: 'Ö', anlatim: 'Sekiz bacaklı ağ ustası', zorluk: 1 },
  { no: 13, dil: 'tr', deste: 'temel', soz: 'inek', harf: 'N', anlatim: 'Süt fabrikası: mööö!', zorluk: 1 },
  { no: 14, dil: 'tr', deste: 'temel', soz: 'horoz', harf: 'O', anlatim: 'Sabahları herkesi uyandıran ibikli kuş', zorluk: 1 },
  { no: 15, dil: 'tr', deste: 'temel', soz: 'tavşan', harf: 'T', anlatim: 'Havuç kemiren zıpzıp', zorluk: 1 },
  { no: 16, dil: 'tr', deste: 'temel', soz: 'maymun', harf: 'M', anlatim: 'Dalda zıplayan, tüylü şakacı', zorluk: 1 },
  { no: 17, dil: 'tr', deste: 'temel', soz: 'saat', harf: 'A', anlatim: 'Tik tik ilerliyor, hiç durmuyor', zorluk: 1 },
  { no: 18, dil: 'tr', deste: 'temel', soz: 'televizyon', harf: 'E', anlatim: 'Kumandayla açılan büyülü kutu', zorluk: 1 },
  { no: 19, dil: 'tr', deste: 'temel', soz: 'gözlük', harf: 'G', anlatim: 'Burnunun üstündeki iki cam pencere', zorluk: 1 },
  { no: 20, dil: 'tr', deste: 'temel', soz: 'ayakkabı', harf: 'Y', anlatim: 'Bağcıklı, topuklu, çift çift satılır', zorluk: 1 },
  { no: 21, dil: 'tr', deste: 'temel', soz: 'dondurma', harf: 'D', anlatim: 'Külahta eriyen soğuk yaz tatlısı', zorluk: 1 },
  { no: 22, dil: 'tr', deste: 'temel', soz: 'karpuz', harf: 'A', anlatim: 'Dışı yeşil, içi kırmızı, çekirdekli', zorluk: 1 },
  { no: 23, dil: 'tr', deste: 'temel', soz: 'simit', harf: 'İ', anlatim: 'Susamlı halka, çayın can yoldaşı', zorluk: 1 },
  { no: 24, dil: 'tr', deste: 'temel', soz: 'yumurta', harf: 'Y', anlatim: 'Tavuktan önce mi, sonra mı?', zorluk: 1 },
  { no: 25, dil: 'tr', deste: 'temel', soz: 'okul', harf: 'O', anlatim: 'Ders, zil, ödev, sıra', zorluk: 1 },
  { no: 26, dil: 'tr', deste: 'meslekler', soz: 'itfaiyeci', harf: 'İ', anlatim: 'Yangına koşan hortumlu kahraman', zorluk: 1 },
  { no: 27, dil: 'tr', deste: 'meslekler', soz: 'aşçı', harf: 'A', anlatim: 'Önlüklü, kepçeli lezzet yönetmeni', zorluk: 1 },
  { no: 28, dil: 'tr', deste: 'cocuk', soz: 'uçurtma', harf: 'U', anlatim: 'Rüzgârla yükselen ipli kâğıt', zorluk: 1 },
  { no: 29, dil: 'tr', deste: 'cocuk', soz: 'salıncak', harf: 'A', anlatim: 'İleri geri, gökyüzüne bir tekme', zorluk: 1 },
  { no: 30, dil: 'tr', deste: 'cocuk', soz: 'hayalet', harf: 'E', anlatim: 'Çarşaflı, gıcırtılı, «Bööö!» diyor', zorluk: 1 },
  { no: 31, dil: 'tr', deste: 'cocuk', soz: 'korsan', harf: 'R', anlatim: 'Tek gözü bantlı, papağanlı gemici', zorluk: 1 },
  { no: 32, dil: 'tr', deste: 'cocuk', soz: 'dinozor', harf: 'O', anlatim: 'Tavuğun eski dev akrabası', zorluk: 1 },
  { no: 33, dil: 'tr', deste: 'spor', soz: 'futbol', harf: 'F', anlatim: 'Yirmi iki kişinin tek top kavgası', zorluk: 1 },
  { no: 34, dil: 'tr', deste: 'spor', soz: 'hakem', harf: 'E', anlatim: 'Düdüklü, kartlı, sahanın patronu', zorluk: 1 },
  { no: 35, dil: 'tr', deste: 'mutfak', soz: 'tencere', harf: 'E', anlatim: 'Ocakta fokurdayan kapaklı kap', zorluk: 1 },
  { no: 36, dil: 'tr', deste: 'mutfak', soz: 'çatal', harf: 'Ç', anlatim: 'Dört dişli, kaşığın kardeşi', zorluk: 1 },
  { no: 37, dil: 'tr', deste: 'mutfak', soz: 'çaydanlık', harf: 'Ç', anlatim: 'İki katlı demleme kulesi', zorluk: 1 },
  { no: 38, dil: 'tr', deste: 'temel', soz: 'yıldız', harf: 'Y', anlatim: 'Gece tepede göz kırpan ışık', zorluk: 1 },
  { no: 39, dil: 'tr', deste: 'temel', soz: 'bulut', harf: 'T', anlatim: 'Gökyüzünün beyaz koyunları', zorluk: 1 },
  { no: 40, dil: 'tr', deste: 'temel', soz: 'balon', harf: 'B', anlatim: 'Uçup gitmesin diye ipini sıkı tut', zorluk: 1 },
  { no: 41, dil: 'tr', deste: 'temel', soz: 'kitap', harf: 'K', anlatim: 'Sayfaları çevrilen dilsiz anlatıcı', zorluk: 1 },
  { no: 42, dil: 'tr', deste: 'temel', soz: 'ağaç', harf: 'A', anlatim: 'Kökü yerde, tepesi yüksekte, yeşil dev', zorluk: 1 },
  { no: 43, dil: 'tr', deste: 'temel', soz: 'piyano', harf: 'P', anlatim: 'Siyah beyaz tuşlu salon çalgısı', zorluk: 1 },
  { no: 44, dil: 'tr', deste: 'temel', soz: 'gitar', harf: 'G', anlatim: 'Altı telli, kampta şarkı arkadaşı', zorluk: 1 },
  { no: 45, dil: 'tr', deste: 'temel', soz: 'kraliçe', harf: 'K', anlatim: 'Arıların annesi, tacı başında', zorluk: 1 },
  { no: 46, dil: 'tr', deste: 'temel', soz: 'sincap', harf: 'S', anlatim: 'Ceviz toplayan, kuyruğu kabarık', zorluk: 1 },
  { no: 47, dil: 'tr', deste: 'temel', soz: 'timsah', harf: 'T', anlatim: 'Gözyaşı yalan, dişleri gerçek', zorluk: 1 },
  { no: 48, dil: 'tr', deste: 'cocuk', soz: 'deniz kızı', harf: 'D', anlatim: 'Yarısı insan, yarısı pullu kuyruk', zorluk: 1 },
  { no: 49, dil: 'tr', deste: 'cocuk', soz: 'sihirbaz', harf: 'S', anlatim: 'Abrakadabra deyip şapkadan güvercin çıkartan', zorluk: 1 },
  { no: 50, dil: 'tr', deste: 'meslekler', soz: 'garson', harf: 'G', anlatim: 'Tepsiyle masadan masaya koşan', zorluk: 1 },
  { no: 51, dil: 'tr', deste: 'meslekler', soz: 'pilot', harf: 'P', anlatim: 'Gökyüzü şoförü', zorluk: 1 },
  // Türkçe — zorluk 2
  { no: 52, dil: 'tr', deste: 'temel', soz: 'ayna', harf: 'A', anlatim: 'Seni tersinden gösteren yüzey', zorluk: 2 },
  { no: 53, dil: 'tr', deste: 'temel', soz: 'kelebek', harf: 'A', anlatim: 'Tırtıldı, şimdi uçuyor', zorluk: 2 },
  { no: 54, dil: 'tr', deste: 'temel', soz: 'pusula', harf: 'A', anlatim: 'Hep kuzeyi gösteren ibre', zorluk: 2 },
  { no: 55, dil: 'tr', deste: 'temel', soz: 'gökkuşağı', harf: 'Ş', anlatim: 'Yağmurdan sonra beliren yedi renkli yay', zorluk: 2 },
  { no: 56, dil: 'tr', deste: 'temel', soz: 'şimşek', harf: 'Ş', anlatim: 'Gürültüden önce çakan parlak zikzak', zorluk: 2 },
  { no: 57, dil: 'tr', deste: 'temel', soz: 'mıknatıs', harf: 'M', anlatim: 'Ataşları kendine çeken', zorluk: 2 },
  { no: 58, dil: 'tr', deste: 'temel', soz: 'asansör', harf: 'R', anlatim: 'Düğmeye bas, kat kat çık', zorluk: 2 },
  { no: 59, dil: 'tr', deste: 'temel', soz: 'merdiven', harf: 'E', anlatim: 'Basamak basamak yukarı çıkış', zorluk: 2 },
  { no: 60, dil: 'tr', deste: 'temel', soz: 'pasaport', harf: 'P', anlatim: 'Mühür biriktiren gezgin defteri', zorluk: 2 },
  { no: 61, dil: 'tr', deste: 'temel', soz: 'valiz', harf: 'Z', anlatim: 'Tekerlekli tatil çantası', zorluk: 2 },
  { no: 62, dil: 'tr', deste: 'temel', soz: 'denizaltı', harf: 'İ', anlatim: 'Suya batan sarı tekne', zorluk: 2 },
  { no: 63, dil: 'tr', deste: 'temel', soz: 'roket', harf: 'O', anlatim: 'Geri sayım bitince uzaya fırlar', zorluk: 2 },
  { no: 64, dil: 'tr', deste: 'temel', soz: 'satranç', harf: 'Ş', anlatim: 'Vezir, kale, at ve mat', zorluk: 2 },
  { no: 65, dil: 'tr', deste: 'temel', soz: 'bulmaca', harf: 'B', anlatim: 'Soldan sağa, yukarıdan aşağıya', zorluk: 2 },
  { no: 66, dil: 'tr', deste: 'temel', soz: 'teleskop', harf: 'T', anlatim: 'Gökyüzünü yakına çeken uzun dürbün', zorluk: 2 },
  { no: 67, dil: 'tr', deste: 'temel', soz: 'gazete', harf: 'G', anlatim: 'Sabah okunan, akşam paket olan kâğıt', zorluk: 2 },
  { no: 68, dil: 'tr', deste: 'temel', soz: 'fermuar', harf: 'F', anlatim: 'Montu dişleriyle kapatan şerit', zorluk: 2 },
  { no: 69, dil: 'tr', deste: 'temel', soz: 'eldiven', harf: 'E', anlatim: 'Parmak parmak kış çorabı', zorluk: 2 },
  { no: 70, dil: 'tr', deste: 'temel', soz: 'atkı', harf: 'K', anlatim: 'Boynuna dolanan uzun yün şerit', zorluk: 2 },
  { no: 71, dil: 'tr', deste: 'temel', soz: 'terlik', harf: 'T', anlatim: 'Evde giyilen, arkası açık pabuç', zorluk: 2 },
  { no: 72, dil: 'tr', deste: 'temel', soz: 'metro', harf: 'M', anlatim: 'Şehrin altından geçen tren', zorluk: 2 },
  { no: 73, dil: 'tr', deste: 'temel', soz: 'müze', harf: 'Z', anlatim: 'Dokunmak yasak, bakmak serbest yer', zorluk: 2 },
  { no: 74, dil: 'tr', deste: 'temel', soz: 'kütüphane', harf: 'K', anlatim: 'Şşş! Sayfalar uyuyor', zorluk: 2 },
  { no: 75, dil: 'tr', deste: 'cocuk', soz: 'oyuncak ayı', harf: 'A', anlatim: 'Pelüş, tüylü, uyku dostu', zorluk: 2 },
  { no: 76, dil: 'tr', deste: 'temel', soz: 'ampul', harf: 'P', anlatim: 'Fikir gelince kafanda yanan ışık', zorluk: 2 },
  { no: 77, dil: 'tr', deste: 'temel', soz: 'kulaklık', harf: 'K', anlatim: 'Müziği yalnız sana çalan', zorluk: 2 },
  { no: 78, dil: 'tr', deste: 'temel', soz: 'davul', harf: 'D', anlatim: 'Zurnanın ayrılmaz eşi', zorluk: 2 },
  { no: 79, dil: 'tr', deste: 'temel', soz: 'doğum günü', harf: 'D', anlatim: 'Mumlu pasta, iyi ki varsın', zorluk: 2 },
  { no: 80, dil: 'tr', deste: 'temel', soz: 'lokum', harf: 'L', anlatim: 'Pudra şekeri giymiş yumuşak küp', zorluk: 2 },
  { no: 81, dil: 'tr', deste: 'temel', soz: 'kahvaltı', harf: 'K', anlatim: 'Sabahın en önemli sofrası', zorluk: 2 },
  { no: 82, dil: 'tr', deste: 'temel', soz: 'pilav', harf: 'P', anlatim: 'Tane tane, tereyağlı, kuru fasulye eşi', zorluk: 2 },
  { no: 83, dil: 'tr', deste: 'temel', soz: 'limon', harf: 'L', anlatim: 'Hayat sana bunu verirse şerbet yap', zorluk: 2 },
  { no: 84, dil: 'tr', deste: 'temel', soz: 'mısır', harf: 'M', anlatim: 'Koçanı közde, tanesi patlayınca beyaz', zorluk: 2 },
  { no: 85, dil: 'tr', deste: 'temel', soz: 'fındık', harf: 'F', anlatim: 'Kabuklu, yuvarlak, çikolatanın can dostu', zorluk: 2 },
  { no: 86, dil: 'tr', deste: 'temel', soz: 'kirpi', harf: 'İ', anlatim: 'Sırtı ok dolu ufaklık', zorluk: 2 },
  { no: 87, dil: 'tr', deste: 'temel', soz: 'baykuş', harf: 'B', anlatim: 'Gece uyumayan, «Uhu!» diyen kanatlı', zorluk: 2 },
  { no: 88, dil: 'tr', deste: 'temel', soz: 'halı', harf: 'H', anlatim: 'Uçanı masallarda, düzü salonda', zorluk: 2 },
  { no: 89, dil: 'tr', deste: 'temel', soz: 'fotoğraf', harf: 'F', anlatim: 'Gülümse, «Peynir!» de, çek', zorluk: 2 },
  { no: 90, dil: 'tr', deste: 'temel', soz: 'harita', harf: 'H', anlatim: 'Dünyayı katlayıp cebe koy', zorluk: 2 },
  { no: 91, dil: 'tr', deste: 'meslekler', soz: 'astronot', harf: 'T', anlatim: 'Ay\'da yürüyen ilk insanlar', zorluk: 2 },
  { no: 92, dil: 'tr', deste: 'meslekler', soz: 'dalgıç', harf: 'D', anlatim: 'Tüp ve paletle su altına inen', zorluk: 2 },
  { no: 93, dil: 'tr', deste: 'meslekler', soz: 'balıkçı', harf: 'B', anlatim: 'Oltasıyla geçimini sağlayan', zorluk: 2 },
  { no: 94, dil: 'tr', deste: 'mutfak', soz: 'menemen', harf: 'M', anlatim: 'Soğanlı olur, soğansız olur; kavga çıkar', zorluk: 2 },
  { no: 95, dil: 'tr', deste: 'mutfak', soz: 'lahmacun', harf: 'L', anlatim: 'İnce hamur, kıyma, maydanozu sar', zorluk: 2 },
  { no: 96, dil: 'tr', deste: 'mutfak', soz: 'baklava', harf: 'B', anlatim: 'Kat kat, şuruplu, fıstıklı tatlı', zorluk: 2 },
  { no: 97, dil: 'tr', deste: 'mutfak', soz: 'mantı', harf: 'M', anlatim: 'Yoğurtlu, ufacık bohçalar', zorluk: 2 },
  { no: 98, dil: 'tr', deste: 'spor', soz: 'penaltı', harf: 'P', anlatim: 'On bir adım, kaleci ve sen', zorluk: 2 },
  { no: 99, dil: 'tr', deste: 'spor', soz: 'kupa', harf: 'U', anlatim: 'Şampiyonların havaya kaldırdığı parlak şey', zorluk: 2 },
  { no: 100, dil: 'tr', deste: 'spor', soz: 'ofsayt', harf: 'S', anlatim: 'Bayrak kalktı, gol iptal', zorluk: 2 },
  { no: 101, dil: 'tr', deste: 'cocuk', soz: 'palyaço', harf: 'P', anlatim: 'Kırmızı burunlu sirk komedyeni', zorluk: 2 },
  { no: 102, dil: 'tr', deste: 'cocuk', soz: 'saklambaç', harf: 'S', anlatim: 'Ebe gözünü yumar, biz gizleniriz', zorluk: 2 },
  { no: 103, dil: 'tr', deste: 'cocuk', soz: 'ejderha', harf: 'E', anlatim: 'Ağzından kor saçan, kanatlı, pullu', zorluk: 2 },
  { no: 104, dil: 'tr', deste: 'cocuk', soz: 'hazine', harf: 'H', anlatim: 'X işaretli yerde gömülü servet', zorluk: 2 },
  { no: 105, dil: 'tr', deste: 'cocuk', soz: 'tebeşir', harf: 'E', anlatim: 'Yazı tahtasında gıcırdayan ak çubuk', zorluk: 2 },
  { no: 106, dil: 'tr', deste: 'cocuk', soz: 'yapboz', harf: 'Y', anlatim: 'Parça parça bütünü tamamla', zorluk: 2 },
  { no: 107, dil: 'tr', deste: 'temel', soz: 'şans', harf: 'Ş', anlatim: 'Dört yapraklı yonca getirir', zorluk: 2 },
  { no: 108, dil: 'tr', deste: 'temel', soz: 'teneffüs', harf: 'T', anlatim: 'Zil çalınca bahçeye koş!', zorluk: 2 },
  // Türkçe — zorluk 3
  { no: 109, dil: 'tr', deste: 'temel', soz: 'kum saati', harf: 'S', anlatim: 'Tane tane akan zaman', zorluk: 3 },
  { no: 110, dil: 'tr', deste: 'temel', soz: 'yankı', harf: 'Y', anlatim: 'Dağa bağır, dağ cevap verir', zorluk: 3 },
  { no: 111, dil: 'tr', deste: 'temel', soz: 'gölge', harf: 'G', anlatim: 'Peşini bırakmayan karanlık ikizin', zorluk: 3 },
  { no: 112, dil: 'tr', deste: 'temel', soz: 'serap', harf: 'S', anlatim: 'Çölde gözüne görünen yalancı göl', zorluk: 3 },
  { no: 113, dil: 'tr', deste: 'temel', soz: 'girdap', harf: 'G', anlatim: 'Suyun içinde dönen huni', zorluk: 3 },
  { no: 114, dil: 'tr', deste: 'temel', soz: 'çığ', harf: 'Ç', anlatim: 'Dağdan kopan dev kartopu', zorluk: 3 },
  { no: 115, dil: 'tr', deste: 'temel', soz: 'hapşırık', harf: 'H', anlatim: 'Çok yaşa dedirten patlama', zorluk: 3 },
  { no: 116, dil: 'tr', deste: 'temel', soz: 'hıçkırık', harf: 'H', anlatim: 'Su iç, nefesini tut, geçer', zorluk: 3 },
  { no: 117, dil: 'tr', deste: 'temel', soz: 'horultu', harf: 'O', anlatim: 'Uyuyanın gece çıkardığı gürültü', zorluk: 3 },
  { no: 118, dil: 'tr', deste: 'temel', soz: 'fısıltı', harf: 'F', anlatim: 'Kimse duymasın diye alçaltılmış ses', zorluk: 3 },
  { no: 119, dil: 'tr', deste: 'temel', soz: 'tembellik', harf: 'T', anlatim: 'Hep yarın yaparım diyenin derdi', zorluk: 3 },
  { no: 120, dil: 'tr', deste: 'temel', soz: 'unutkanlık', harf: 'U', anlatim: 'Az önce ne diyecektim?', zorluk: 3 },
  { no: 121, dil: 'tr', deste: 'temel', soz: 'kıskançlık', harf: 'K', anlatim: 'Yeşil gözlü canavar', zorluk: 3 },
  { no: 122, dil: 'tr', deste: 'temel', soz: 'sessizlik', harf: 'S', anlatim: 'Altın olan şey; konuşmak gümüş', zorluk: 3 },
  { no: 123, dil: 'tr', deste: 'temel', soz: 'rüya', harf: 'R', anlatim: 'Uykuda izlenen film', zorluk: 3 },
  { no: 124, dil: 'tr', deste: 'temel', soz: 'merak', harf: 'M', anlatim: 'Kapı aralığından bakan duygu', zorluk: 3 },
  { no: 125, dil: 'tr', deste: 'temel', soz: 'uydu', harf: 'U', anlatim: 'Dünyanın çevresinde dönen yapay ay', zorluk: 3 },
  { no: 126, dil: 'tr', deste: 'temel', soz: 'kara delik', harf: 'K', anlatim: 'Işığı bile yutan uzay boşluğu', zorluk: 3 },
  { no: 127, dil: 'tr', deste: 'temel', soz: 'kuyruklu yıldız', harf: 'Y', anlatim: 'Saçlı, parlak gece gezgini', zorluk: 3 },
  { no: 128, dil: 'tr', deste: 'temel', soz: 'uçurum', harf: 'U', anlatim: 'Kenarından bakınca başın döner', zorluk: 3 },
  { no: 129, dil: 'tr', deste: 'temel', soz: 'labirent', harf: 'L', anlatim: 'Girişi basit, çıkışı zor', zorluk: 3 },
  { no: 130, dil: 'tr', deste: 'temel', soz: 'kaldıraç', harf: 'D', anlatim: 'Bana bir nokta verin, yeri oynatırım', zorluk: 3 },
  { no: 131, dil: 'tr', deste: 'temel', soz: 'prizma', harf: 'P', anlatim: 'Beyaz ışığı yedi renge ayıran cam', zorluk: 3 },
  { no: 132, dil: 'tr', deste: 'temel', soz: 'mikroskop', harf: 'M', anlatim: 'Hücreleri dev gösteren laboratuvar aleti', zorluk: 3 },
  { no: 133, dil: 'tr', deste: 'temel', soz: 'daktilo', harf: 'D', anlatim: 'Tıkır tıkır yazan eski klavye', zorluk: 3 },
  { no: 134, dil: 'tr', deste: 'temel', soz: 'plak', harf: 'P', anlatim: 'İğne altında dönen siyah şarkı tabağı', zorluk: 3 },
  { no: 135, dil: 'tr', deste: 'temel', soz: 'yüksük', harf: 'Y', anlatim: 'İğne batmasın, parmak kalkanı', zorluk: 3 },
  { no: 136, dil: 'tr', deste: 'temel', soz: 'papyon', harf: 'P', anlatim: 'Kravatın fiyonk kılıklı kuzeni', zorluk: 3 },
  { no: 137, dil: 'tr', deste: 'temel', soz: 'mızıka', harf: 'M', anlatim: 'Ağızla çalınan cep boyu çalgı', zorluk: 3 },
  { no: 138, dil: 'tr', deste: 'temel', soz: 'kunduz', harf: 'Z', anlatim: 'Dişleriyle baraj kuran mühendis', zorluk: 3 },
  { no: 139, dil: 'tr', deste: 'temel', soz: 'köstebek', harf: 'B', anlatim: 'Toprak altında tünel kazan, gözü zayıf', zorluk: 3 },
  { no: 140, dil: 'tr', deste: 'mutfak', soz: 'oklava', harf: 'O', anlatim: 'İnce hamur açan uzun tahta', zorluk: 3 },
  { no: 141, dil: 'tr', deste: 'mutfak', soz: 'cezve', harf: 'C', anlatim: 'Türk kahvesinin köpük ustası', zorluk: 3 },
  { no: 142, dil: 'tr', deste: 'mutfak', soz: 'kaymak', harf: 'K', anlatim: 'Ballı, sütün en tatlı yüzü', zorluk: 3 },
  { no: 143, dil: 'tr', deste: 'spor', soz: 'rövaşata', harf: 'R', anlatim: 'Takla atıp kafanın üstünden şut', zorluk: 3 },
  { no: 144, dil: 'tr', deste: 'spor', soz: 'fotofiniş', harf: 'F', anlatim: 'Çizgiyi hangisi önce geçti?', zorluk: 3 },
  { no: 145, dil: 'tr', deste: 'meslekler', soz: 'vantrilok', harf: 'V', anlatim: 'Ağzını oynatmadan kuklasıyla konuşan', zorluk: 3 },
  { no: 146, dil: 'tr', deste: 'meslekler', soz: 'çilingir', harf: 'Ç', anlatim: 'Kilitli kapıların kurtarıcısı', zorluk: 3 },
  { no: 147, dil: 'tr', deste: 'meslekler', soz: 'dublör', harf: 'D', anlatim: 'Tehlikeli sahnelerin gizli kahramanı', zorluk: 3 },
  { no: 148, dil: 'tr', deste: 'cocuk', soz: 'tekerleme', harf: 'T', anlatim: 'Bir berber bir berbere', zorluk: 3 },
  { no: 149, dil: 'tr', deste: 'cocuk', soz: 'origami', harf: 'O', anlatim: 'Kâğıdı katlayıp kuğu yapma sanatı', zorluk: 3 },
  { no: 150, dil: 'tr', deste: 'cocuk', soz: 'mamut', harf: 'M', anlatim: 'Buz çağının uzun tüylü devi', zorluk: 3 },
  // English — difficulty 1
  { no: 151, dil: 'en', deste: 'basic', soz: 'cat', harf: 'E', anlatim: 'Purring furry pal', zorluk: 1 },
  { no: 152, dil: 'en', deste: 'basic', soz: 'umbrella', harf: 'O', anlatim: 'Shield against the drizzle', zorluk: 1 },
  { no: 153, dil: 'en', deste: 'basic', soz: 'snowman', harf: 'S', anlatim: 'Cold white guy with a carrot', zorluk: 1 },
  { no: 154, dil: 'en', deste: 'basic', soz: 'bicycle', harf: 'N', anlatim: 'Two wheels, pedals, a bell', zorluk: 1 },
  { no: 155, dil: 'en', deste: 'basic', soz: 'dog', harf: 'O', anlatim: 'Barks at the mailman', zorluk: 1 },
  { no: 156, dil: 'en', deste: 'basic', soz: 'penguin', harf: 'G', anlatim: 'Tuxedo bird that can\'t fly', zorluk: 1 },
  { no: 157, dil: 'en', deste: 'basic', soz: 'elephant', harf: 'T', anlatim: 'Huge gray ears, nose hose', zorluk: 1 },
  { no: 158, dil: 'en', deste: 'basic', soz: 'giraffe', harf: 'F', anlatim: 'Spotted, with the longest neck', zorluk: 1 },
  { no: 159, dil: 'en', deste: 'basic', soz: 'sun', harf: 'N', anlatim: 'Hot yellow ball up above', zorluk: 1 },
  { no: 160, dil: 'en', deste: 'basic', soz: 'rainbow', harf: 'A', anlatim: 'Seven colors in the sky', zorluk: 1 },
  { no: 161, dil: 'en', deste: 'basic', soz: 'pizza', harf: 'Z', anlatim: 'Round, cheesy, cut in slices', zorluk: 1 },
  { no: 162, dil: 'en', deste: 'basic', soz: 'ice cream', harf: 'I', anlatim: 'Cold sweet scoops on a cone', zorluk: 1 },
  { no: 163, dil: 'en', deste: 'basic', soz: 'teacher', harf: 'T', anlatim: 'Grades your homework', zorluk: 1 },
  { no: 164, dil: 'en', deste: 'basic', soz: 'clock', harf: 'O', anlatim: 'Tick tick, its hands never rest', zorluk: 1 },
  { no: 165, dil: 'en', deste: 'basic', soz: 'butterfly', harf: 'B', anlatim: 'Caterpillar, all grown up', zorluk: 1 },
  { no: 166, dil: 'en', deste: 'basic', soz: 'doctor', harf: 'O', anlatim: 'Apple a day keeps them away', zorluk: 1 },
  { no: 167, dil: 'en', deste: 'basic', soz: 'chicken', harf: 'K', anlatim: 'Why did it cross the road?', zorluk: 1 },
  { no: 168, dil: 'en', deste: 'basic', soz: 'kite', harf: 'K', anlatim: 'Flies high on a string', zorluk: 1 },
  { no: 169, dil: 'en', deste: 'basic', soz: 'breakfast', harf: 'B', anlatim: 'First meal of the day', zorluk: 1 },
  // English — difficulty 2
  { no: 170, dil: 'en', deste: 'basic', soz: 'mirror', harf: 'R', anlatim: 'Shows you you, flipped', zorluk: 2 },
  { no: 171, dil: 'en', deste: 'basic', soz: 'volcano', harf: 'O', anlatim: 'A hill that spits fire', zorluk: 2 },
  { no: 172, dil: 'en', deste: 'basic', soz: 'lighthouse', harf: 'L', anlatim: 'Tower that warns ships at night', zorluk: 2 },
  { no: 173, dil: 'en', deste: 'basic', soz: 'calendar', harf: 'E', anlatim: 'Days, months, holidays on a wall', zorluk: 2 },
  { no: 174, dil: 'en', deste: 'basic', soz: 'scissors', harf: 'C', anlatim: 'Beat paper, lose to stone', zorluk: 2 },
  { no: 175, dil: 'en', deste: 'basic', soz: 'elevator', harf: 'E', anlatim: 'Push a button, rising room', zorluk: 2 },
  { no: 176, dil: 'en', deste: 'basic', soz: 'passport', harf: 'P', anlatim: 'Booklet for crossing borders', zorluk: 2 },
  { no: 177, dil: 'en', deste: 'basic', soz: 'telescope', harf: 'O', anlatim: 'Brings distant stars near', zorluk: 2 },
  { no: 178, dil: 'en', deste: 'basic', soz: 'hedgehog', harf: 'H', anlatim: 'Spiky ball, curls up small', zorluk: 2 },
  { no: 179, dil: 'en', deste: 'basic', soz: 'octopus', harf: 'C', anlatim: 'Eight arms, three hearts, blue blood', zorluk: 2 },
  { no: 180, dil: 'en', deste: 'basic', soz: 'squirrel', harf: 'R', anlatim: 'Hides nuts, then loses them', zorluk: 2 },
  { no: 181, dil: 'en', deste: 'basic', soz: 'turtle', harf: 'T', anlatim: 'Slow walker, home on his back', zorluk: 2 },
  { no: 182, dil: 'en', deste: 'basic', soz: 'headphones', harf: 'E', anlatim: 'Music for only you', zorluk: 2 },
  { no: 183, dil: 'en', deste: 'basic', soz: 'birthday', harf: 'B', anlatim: 'Candles, cake, and a song', zorluk: 2 },
  { no: 184, dil: 'en', deste: 'basic', soz: 'envelope', harf: 'V', anlatim: 'Paper jacket for a letter', zorluk: 2 },
  { no: 185, dil: 'en', deste: 'basic', soz: 'zipper', harf: 'Z', anlatim: 'Teeth that close your jacket', zorluk: 2 },
  { no: 186, dil: 'en', deste: 'basic', soz: 'spider', harf: 'D', anlatim: 'Eight legs, a silky web', zorluk: 2 },
  // English — difficulty 3
  { no: 187, dil: 'en', deste: 'basic', soz: 'echo', harf: 'E', anlatim: 'Canyon shouts back at you', zorluk: 3 },
  { no: 188, dil: 'en', deste: 'basic', soz: 'shadow', harf: 'D', anlatim: 'Your silent black twin', zorluk: 3 },
  { no: 189, dil: 'en', deste: 'basic', soz: 'dream', harf: 'D', anlatim: 'A movie in your sleep', zorluk: 3 },
  { no: 190, dil: 'en', deste: 'basic', soz: 'whisper', harf: 'W', anlatim: 'Secret said softly into an ear', zorluk: 3 },
  { no: 191, dil: 'en', deste: 'basic', soz: 'sneeze', harf: 'Z', anlatim: 'Achoo! Bless you!', zorluk: 3 },
  { no: 192, dil: 'en', deste: 'basic', soz: 'hiccup', harf: 'C', anlatim: 'Hold your breath and drink water', zorluk: 3 },
  { no: 193, dil: 'en', deste: 'basic', soz: 'hourglass', harf: 'S', anlatim: 'Time falling grain by grain', zorluk: 3 },
  { no: 194, dil: 'en', deste: 'basic', soz: 'maze', harf: 'Z', anlatim: 'Easy to enter, hard to exit', zorluk: 3 },
  { no: 195, dil: 'en', deste: 'basic', soz: 'avalanche', harf: 'A', anlatim: 'Tons of white fluff rolling downhill', zorluk: 3 },
  { no: 196, dil: 'en', deste: 'basic', soz: 'mirage', harf: 'M', anlatim: 'Fake water in the desert', zorluk: 3 },
  { no: 197, dil: 'en', deste: 'basic', soz: 'eclipse', harf: 'C', anlatim: 'Daytime goes dark for a moment', zorluk: 3 },
  { no: 198, dil: 'en', deste: 'basic', soz: 'luck', harf: 'K', anlatim: 'Four-leaf clover brings it', zorluk: 3 },
  { no: 199, dil: 'en', deste: 'basic', soz: 'curiosity', harf: 'C', anlatim: 'Why? How? What\'s inside?', zorluk: 3 },
  { no: 200, dil: 'en', deste: 'basic', soz: 'stapler', harf: 'S', anlatim: 'Chomp! Paper pinned at the corner', zorluk: 3 },
]);

// İlk ekran ve öğretici için örnek anlatımlar: arşiv numaraları (dil → numaralar; ilki ana ekranın örneği). Her
// biri kısa, kolay (zorluk 1–2) ve esprili. Arayüz anlatımı archiveEntry(no) ile okur.
export const ILK_EKRAN = Object.freeze({
  tr: Object.freeze([1, 8, 24, 47, 64, 74]),
  en: Object.freeze([151, 155, 167, 170, 174]),
});
