// Süzgeç listesi: anlatımda ve gizli sözcükte kabul edilmeyen sözcükler.
// Biçim: docs/icerik-bicimi.md §5. Liste kurarken (kurucu cihazında) ve açarken (alıcı cihazında) aynı biçimde
// çalışır; sunucu kopyasına girer (KOORDINASYON.md §18). Her girdinin nedeni, kipi ve bilinen yanlış pozitifi:
// tools/icerik/suzgec-notlari.md. Dış liste kopyalanmadı; girdiler tek tek seçildi ve yanlış pozitif taramasından
// geçti (tools/icerik/yanlis-pozitif.mjs --suzgec).
//
// s      : sözcük, küçük harf, Türkçe harflerle
// kip    : 'kok'    → sözcük ve bütün ekli, türemiş, bitişik hâlleri (uzun kökte katı önek kuralı; 4 harf ve uzun
//                     Türkçe girdide ünsüz yumuşaması da: "salağı", "pezevengi")
//          'cekim'  → yalnız kendisi ve çekimleri (TR çoğul, iyelik, durum, ek eylem; EN -s, -es, -ies): "zenciler",
//                     "dicks"; türemiş ve bitişik hâlleri değil ("seksen", "cocktail" serbest)
//          'fiil'   → Türkçe fiil kökü: bütün eylem çekimleri ("sikti", "sikmek", "siksin") ve adın çekimleri
//          'tam'    → yalnız sözcüğün kendisi (kısa ve çok anlamlı sözcükler: "am", "amk")
//          'icerir' → sözcüğün içinde herhangi bir yerde geçmesi
// katla  : true (varsayılan) ise ASCII'ye katlanmış iskelette karşılaştırılır (ı = i, ş = s);
//          false ise Türkçe harfler korunur ("sik" engellenir, "sık" engellenmez)
// dil    : ek zincirinin hangi dilin kurallarıyla tanınacağı ('tr' | 'en')
// uygula : hangi kipteki bulmacalarda uygulanır ('tr' | 'en' | '*', varsayılan '*'); "am" İngilizcede olağan sözcüktür
// serbest: bu girdiye takılmayan olağan sözcükler; kendileri ve çekimleri serbesttir ("sıç" → "sıçan", "bok" → "boks")

export const SUZGEC = Object.freeze([
  // Türkçe: hakaret
  { s: 'salak', kip: 'kok', dil: 'tr' },
  { s: 'aptal', kip: 'kok', dil: 'tr' },
  { s: 'ahmak', kip: 'kok', dil: 'tr', serbest: ['ahmakıslatan'] },
  { s: 'gerizekalı', kip: 'kok', dil: 'tr' },
  { s: 'dangalak', kip: 'kok', dil: 'tr' },
  { s: 'dallama', kip: 'kok', dil: 'tr' },
  { s: 'angut', kip: 'kok', dil: 'tr' },
  { s: 'hıyarağası', kip: 'kok', dil: 'tr' },
  { s: 'şerefsiz', kip: 'kok', dil: 'tr' },
  { s: 'haysiyetsiz', kip: 'kok', dil: 'tr' },
  { s: 'namussuz', kip: 'kok', dil: 'tr' },
  { s: 'yavşak', kip: 'kok', dil: 'tr' },
  { s: 'dürzü', kip: 'kok', dil: 'tr' },
  { s: 'gavat', kip: 'kok', dil: 'tr' },
  { s: 'pezevenk', kip: 'kok', dil: 'tr' },
  { s: 'puşt', kip: 'kok', dil: 'tr', katla: false },
  // Türkçe: küfür ve müstehcen
  { s: 'orospu', kip: 'icerir', dil: 'tr' },
  { s: 'kahpe', kip: 'kok', dil: 'tr' },
  { s: 'kaltak', kip: 'kok', dil: 'tr' },
  { s: 'sürtük', kip: 'kok', dil: 'tr' },
  { s: 'fahişe', kip: 'kok', dil: 'tr' },
  { s: 'kancık', kip: 'kok', dil: 'tr' },
  { s: 'ibne', kip: 'kok', dil: 'tr' },
  { s: 'sik', kip: 'fiil', dil: 'tr', katla: false, serbest: ['sikke'] },
  { s: 'sikik', kip: 'kok', dil: 'tr', katla: false },
  { s: 'sikiş', kip: 'kok', dil: 'tr', katla: false },
  { s: 'siktir', kip: 'kok', dil: 'tr', katla: false },
  { s: 'sikerim', kip: 'kok', dil: 'tr', katla: false },
  { s: 'sikeyim', kip: 'kok', dil: 'tr', katla: false },
  { s: 'amk', kip: 'tam', dil: 'tr' },
  { s: 'aq', kip: 'tam', dil: 'tr' },
  { s: 'am', kip: 'tam', dil: 'tr', katla: false, uygula: 'tr' },
  { s: 'amına', kip: 'kok', dil: 'tr', katla: false },
  { s: 'amın', kip: 'tam', dil: 'tr', katla: false, uygula: 'tr' },
  { s: 'amını', kip: 'tam', dil: 'tr', katla: false, uygula: 'tr' },
  { s: 'amınız', kip: 'kok', dil: 'tr', katla: false, uygula: 'tr' },
  { s: 'amcık', kip: 'kok', dil: 'tr' },
  { s: 'yarrak', kip: 'kok', dil: 'tr' },
  { s: 'yarak', kip: 'cekim', dil: 'tr' },
  { s: 'taşak', kip: 'kok', dil: 'tr' },
  { s: 'daşşak', kip: 'kok', dil: 'tr' },
  { s: 'göt', kip: 'kok', dil: 'tr', katla: false },
  { s: 'götveren', kip: 'kok', dil: 'tr', katla: false },
  { s: 'götlek', kip: 'kok', dil: 'tr', katla: false },
  { s: 'piç', kip: 'kok', dil: 'tr', katla: false },
  { s: 'oç', kip: 'tam', dil: 'tr', katla: false },
  { s: 'gavur', kip: 'kok', dil: 'tr' },
  // Türkçe: hakaret (ek)
  { s: 'gerzek', kip: 'kok', dil: 'tr' },
  { s: 'embesil', kip: 'kok', dil: 'tr' },
  { s: 'mankafa', kip: 'kok', dil: 'tr' },
  { s: 'beyinsiz', kip: 'kok', dil: 'tr' },
  { s: 'enayi', kip: 'kok', dil: 'tr' },
  { s: 'keriz', kip: 'kok', dil: 'tr' },
  { s: 'lavuk', kip: 'kok', dil: 'tr' },
  { s: 'hödük', kip: 'kok', dil: 'tr' },
  { s: 'kevaşe', kip: 'kok', dil: 'tr' },
  { s: 'şırfıntı', kip: 'kok', dil: 'tr' },
  { s: 'dalyarak', kip: 'kok', dil: 'tr' },
  // Türkçe: küfür, müstehcen ve kısaltmaları (ek)
  { s: 'amq', kip: 'tam', dil: 'tr' },
  { s: 'sktr', kip: 'tam', dil: 'tr' },
  { s: 'mk', kip: 'tam', dil: 'tr' },
  { s: 'sg', kip: 'tam', dil: 'tr', uygula: 'tr' },
  { s: 'skm', kip: 'tam', dil: 'tr' },
  { s: 'skym', kip: 'tam', dil: 'tr' },
  { s: 'amina', kip: 'kok', dil: 'tr', katla: false },
  { s: 'orosbu', kip: 'icerir', dil: 'tr' },
  { s: 'orspu', kip: 'icerir', dil: 'tr' },
  { s: 'oruspu', kip: 'icerir', dil: 'tr' },
  { s: 'bok', kip: 'kok', dil: 'tr', uygula: 'tr', serbest: ['boks'] },
  { s: 'sıç', kip: 'fiil', dil: 'tr', katla: false, serbest: ['sıçan'] },
  { s: 'çük', kip: 'kok', dil: 'tr', katla: false },
  { s: 'penis', kip: 'kok', dil: 'tr' },
  { s: 'vajina', kip: 'kok', dil: 'tr' },
  { s: 'seks', kip: 'cekim', dil: 'tr' },
  { s: 'seksi', kip: 'tam', dil: 'tr' },
  { s: 'erotik', kip: 'kok', dil: 'tr' },
  { s: 'genelev', kip: 'kok', dil: 'tr' },
  { s: 'kerhane', kip: 'kok', dil: 'tr' },
  { s: 'orgazm', kip: 'kok', dil: 'tr' },
  { s: 'mastürb', kip: 'kok', dil: 'tr' },
  { s: 'deyyus', kip: 'kok', dil: 'tr' },
  { s: 'godoş', kip: 'kok', dil: 'tr' },
  { s: 'şıllık', kip: 'kok', dil: 'tr' },
  // Türkçe: nefret söylemi (aşağılayıcı kullanımı baskın olanlar)
  { s: 'zenci', kip: 'cekim', dil: 'tr' },
  { s: 'nonoş', kip: 'kok', dil: 'tr' },
  { s: 'lezbo', kip: 'kok', dil: 'tr' },
  { s: 'kafir', kip: 'kok', dil: 'tr' },
  { s: 'mongol', kip: 'kok', dil: 'tr', uygula: 'tr' },
  { s: 'spastik', kip: 'kok', dil: 'tr' },
  // Türkçe: şiddet ve kendine zarar
  { s: 'geber', kip: 'kok', dil: 'tr' },
  { s: 'tecavüz', kip: 'kok', dil: 'tr' },
  { s: 'intihar', kip: 'kok', dil: 'tr' },
  // İngilizce
  { s: 'fuck', kip: 'icerir', dil: 'en' },
  { s: 'shit', kip: 'icerir', dil: 'en' },
  { s: 'bitch', kip: 'kok', dil: 'en' },
  { s: 'bastard', kip: 'kok', dil: 'en' },
  { s: 'asshole', kip: 'icerir', dil: 'en' },
  { s: 'dickhead', kip: 'kok', dil: 'en' },
  { s: 'cunt', kip: 'icerir', dil: 'en' },
  { s: 'whore', kip: 'kok', dil: 'en' },
  { s: 'slut', kip: 'kok', dil: 'en' },
  { s: 'faggot', kip: 'kok', dil: 'en' },
  { s: 'fag', kip: 'cekim', dil: 'en' },
  { s: 'nigger', kip: 'icerir', dil: 'en' },
  { s: 'nigga', kip: 'icerir', dil: 'en' },
  { s: 'retard', kip: 'kok', dil: 'en' },
  { s: 'wanker', kip: 'kok', dil: 'en' },
  { s: 'twat', kip: 'kok', dil: 'en' },
  { s: 'dumbass', kip: 'kok', dil: 'en' },
  { s: 'jackass', kip: 'kok', dil: 'en' },
  { s: 'idiot', kip: 'kok', dil: 'en' },
  { s: 'moron', kip: 'kok', dil: 'en' },
  { s: 'dick', kip: 'cekim', dil: 'en' },
  { s: 'cock', kip: 'cekim', dil: 'en' },
  { s: 'pussy', kip: 'cekim', dil: 'en' },
  { s: 'piss', kip: 'kok', dil: 'en' },
  // İngilizce: küfür ve müstehcen (ek)
  { s: 'fck', kip: 'icerir', dil: 'en' },
  { s: 'fuk', kip: 'tam', dil: 'en' },
  { s: 'phuck', kip: 'icerir', dil: 'en' },
  { s: 'fvck', kip: 'icerir', dil: 'en' },
  { s: 'biatch', kip: 'kok', dil: 'en' },
  { s: 'stfu', kip: 'tam', dil: 'en' },
  { s: 'wtf', kip: 'tam', dil: 'en' },
  { s: 'ass', kip: 'cekim', dil: 'en' },
  { s: 'badass', kip: 'kok', dil: 'en' },
  { s: 'smartass', kip: 'kok', dil: 'en' },
  { s: 'arse', kip: 'cekim', dil: 'en' },
  { s: 'arsehole', kip: 'icerir', dil: 'en' },
  { s: 'wank', kip: 'kok', dil: 'en' },
  { s: 'cocksucker', kip: 'icerir', dil: 'en' },
  { s: 'douchebag', kip: 'kok', dil: 'en' },
  { s: 'dildo', kip: 'icerir', dil: 'en' },
  { s: 'porn', kip: 'icerir', dil: 'en' },
  { s: 'sex', kip: 'tam', dil: 'en' },
  { s: 'sexy', kip: 'tam', dil: 'en' },
  { s: 'horny', kip: 'tam', dil: 'en' },
  { s: 'boob', kip: 'tam', dil: 'en' },
  { s: 'boobs', kip: 'tam', dil: 'en' },
  { s: 'tits', kip: 'tam', dil: 'en' },
  { s: 'titties', kip: 'kok', dil: 'en' },
  { s: 'vagina', kip: 'kok', dil: 'en' },
  // İngilizce: cinsellik ve istismar (aile oyununda açık kalmamalı)
  { s: 'blowjob', kip: 'icerir', dil: 'en' },
  { s: 'handjob', kip: 'icerir', dil: 'en' },
  { s: 'jizz', kip: 'icerir', dil: 'en' },
  { s: 'cum', kip: 'tam', dil: 'en' },
  { s: 'boner', kip: 'cekim', dil: 'en' },
  { s: 'clit', kip: 'cekim', dil: 'en' },
  { s: 'clitoris', kip: 'kok', dil: 'en' },
  { s: 'orgasm', kip: 'kok', dil: 'en' },
  { s: 'masturbat', kip: 'icerir', dil: 'en' },
  { s: 'milf', kip: 'cekim', dil: 'en' },
  { s: 'thot', kip: 'cekim', dil: 'en' },
  { s: 'skank', kip: 'kok', dil: 'en' },
  { s: 'hooker', kip: 'cekim', dil: 'en' },
  { s: 'shemale', kip: 'kok', dil: 'en' },
  { s: 'pedo', kip: 'cekim', dil: 'en' },
  { s: 'pedophil', kip: 'icerir', dil: 'en' },
  { s: 'incest', kip: 'kok', dil: 'en' },
  // İngilizce: nefret söylemi
  { s: 'chink', kip: 'tam', dil: 'en' },
  { s: 'gook', kip: 'tam', dil: 'en' },
  { s: 'spic', kip: 'tam', dil: 'en' },
  { s: 'kike', kip: 'tam', dil: 'en' },
  { s: 'coon', kip: 'tam', dil: 'en' },
  { s: 'jap', kip: 'tam', dil: 'en' },
  { s: 'paki', kip: 'tam', dil: 'en' },
  { s: 'negro', kip: 'tam', dil: 'en' },
  { s: 'darkie', kip: 'tam', dil: 'en' },
  { s: 'wetback', kip: 'kok', dil: 'en' },
  { s: 'beaner', kip: 'kok', dil: 'en' },
  { s: 'raghead', kip: 'kok', dil: 'en' },
  { s: 'towelhead', kip: 'kok', dil: 'en' },
  { s: 'dyke', kip: 'tam', dil: 'en' },
  { s: 'homo', kip: 'tam', dil: 'en' },
  { s: 'tranny', kip: 'tam', dil: 'en' },
  { s: 'spaz', kip: 'tam', dil: 'en' },
  { s: 'nazi', kip: 'tam', dil: 'en' },
  // İngilizce: şiddet ve kendine zarar
  { s: 'rape', kip: 'tam', dil: 'en' },
  { s: 'raped', kip: 'tam', dil: 'en' },
  { s: 'rapist', kip: 'tam', dil: 'en' },
  { s: 'raping', kip: 'tam', dil: 'en' },
  { s: 'suicide', kip: 'kok', dil: 'en' },
  { s: 'kys', kip: 'tam', dil: 'en' },
]);
