// Ayarlar, Gizlenenler ve Nasıl oynanır metinleri (TR/EN). Bölüm adları inceleme notuyla aynıdır
// (docs/magaza-taslak.md §7: Ayarlar > Mağaza / Gizlenenler / Destekle; Settings > Store / Hidden / Support).

import { letterSuffix, displayLetter } from '../turkce.js';

export const SETTINGS = {
  tr: {
    language: 'Dil',
    langAuto: 'Cihaz dili',
    appearance: 'Görünüm',
    reduceMotion: 'Hareketi azalt',
    reduceMotionNote: 'Sistemdeki Hareketi Azalt ayarı da okunur.',
    themeLabel: 'Tema',
    themeHint: 'Tema, paylaşılan kartta ve oyun ekranlarında görünür; avantaj vermez.',
    safety: 'Gizlilik ve güvenlik',
    hiddenTitle: 'Gizlenenler',
    hiddenCount: (n) => `${n} gizli`,
    hiddenNone: 'Gizlenen yok',
    privacyTitle: 'Gizlilik',
    privacyBody: (counters) =>
      counters
        ? 'Hesap, reklam ve izleme yok. Bulmaca bağlantının # parçasındadır ve sunucumuza gitmez. Cihazdan çıkan yalnız kimliksiz olay sayılarıdır (ör. "bir bulmaca paylaşıldı") ve bildirmeyi seçtiğin anlatım.'
        : 'Hesap, reklam ve izleme yok. Bulmaca bağlantının # parçasındadır ve sunucumuza gitmez. Cihazdan çıkan tek veri, bildirmeyi seçtiğin anlatımdır.',
    privacyLink: 'Gizlilik politikası',
    termsLink: 'Kullanım koşulları',
    helpSection: 'Yardım',
    howToPlay: 'Nasıl oynanır',
    recommendTitle: 'Arkadaşına öner',
    supportPage: 'Destek ve sık sorulanlar',
    supportEmail: 'Destek:',
    storeNewer: 'Kayıtların daha yeni bir sürümle yazılmış; bu sürüm onlara dokunmuyor ve bu oturumda yaptıklarını saklamıyor.',
    notPersistent: 'Bu tarayıcı kayıt tutmuyor (özel pencere olabilir); sayfayı kapatınca ilerlemen silinir.',
    versionLine: (name, v) => `${name} ${v}`,
    hiddenIntro: 'Bildirdiğin ya da gizlediğin anlatımlar ve gizlediğin gönderenler bu cihazda gösterilmez. İstersen buradan geri açabilirsin.',
    hiddenEmpty: 'Gizlediğin anlatım ya da gönderen yok.',
    hiddenClues: 'Anlatımlar',
    hiddenSenders: 'Gönderenler',
    hiddenClueTitle: (l, lang, n) => `${letterSuffix(l, 'siz', lang)} ${n} kelimelik anlatım`,
    hiddenClueGeneric: 'Anlatım',
    reportedOn: 'Bildirildi',
    hiddenOn: 'Gizlendi',
    senderN: (n) => `Gönderen ${n}`,
    unhide: 'Geri aç',
    unhidden: 'Geri açıldı.',
    helpRulesTitle: 'Kurallar',
    helpRule1: 'Üç sözcükten birini seç; yasak harf dağıtılır.',
    helpRule2: 'Sözcüğü o harfi hiç kullanmadan, en çok 8 kelimeyle anlat. Gizli sözcüğün kendisi ve ekli hâlleri de yasak.',
    helpRule3: 'Yalnız harf ve noktalama: rakam, emoji ve başka alfabeden harf yok.',
    helpRule4: 'Arkadaşın 3 hakta bilmeye çalışır. Ekli yazım ("kediler") ve uzun sözcükte tek harflik hata kabul edilir.',
    helpRule5: 'Rövanşta roller döner; yasak harfi rakibin seçer.',
    helpScoreTitle: 'Puan',
    helpScore1: 'Tahmin eden: 1. hakta 3, 2. hakta 2, 3. hakta 1 puan.',
    helpScore2: 'Anlatan: anlatım bilinirse 9 eksi kelime sayısı. Az kelime, çok puan.',
    helpScore3: 'Bilinmeyen anlatım puan getirmez; skor rövanş boyunca taşınır.',
    helpDailyTitle: 'Her gün',
    helpDaily1: 'Günün sözcüğü: herkese aynı sözcük ve harf. Anlat ve paylaş; arkadaşın önce bilsin, sonra daha kısasını yazsın.',
    helpDaily2: 'Çözme arşivi: ekibimizin anlatımlarını arkadaş beklemeden çöz.',
    helpFairTitle: 'Adil ve güvenli',
    helpFair1: 'Hakem Türkçenin eklerini tanır: "kediler", "kitabı", "k e d i" yakalanır; "masal", "karpuz" serbesttir.',
    helpFair2: 'Uygunsuz sözcük süzgeci yazarken ve bağlantı açılırken çalışır. Her anlatımda "Bildir" ve "Gönderenden gelenleri gizle" var.',
    helpFair3: 'Kuran öder, oynayan ödemez: gelen her anlatımı çözmek ücretsizdir.',
  },
  en: {
    language: 'Language',
    langAuto: 'Device language',
    appearance: 'Appearance',
    reduceMotion: 'Reduce motion',
    reduceMotionNote: 'The system Reduce Motion setting is also respected.',
    themeLabel: 'Theme',
    themeHint: 'The theme shows on the shared card and the game screens; it gives no advantage.',
    safety: 'Privacy and safety',
    hiddenTitle: 'Hidden',
    hiddenCount: (n) => `${n} hidden`,
    hiddenNone: 'Nothing hidden',
    privacyTitle: 'Privacy',
    privacyBody: (counters) =>
      counters
        ? 'No account, no ads, no tracking. A puzzle lives in the link fragment (#), which never reaches our server. Only anonymous event counts (like "a puzzle was shared") and clues you choose to report leave this device.'
        : 'No account, no ads, no tracking. A puzzle lives in the link fragment (#), which never reaches our server. The only data that leaves this device is a clue you choose to report.',
    privacyLink: 'Privacy policy',
    termsLink: 'Terms of use',
    helpSection: 'Help',
    howToPlay: 'How to play',
    recommendTitle: 'Tell a friend',
    supportPage: 'Support and FAQ',
    supportEmail: 'Support:',
    storeNewer: 'Your data was saved by a newer version; this version leaves it untouched and does not keep what you do in this session.',
    notPersistent: "This browser isn't keeping data (maybe a private window); your progress is lost when you close the page.",
    versionLine: (name, v) => `${name} ${v}`,
    hiddenIntro: "Clues you reported or hid, and senders you hid, aren't shown on this device. You can unhide them here.",
    hiddenEmpty: "You haven't hidden any clues or senders.",
    hiddenClues: 'Clues',
    hiddenSenders: 'Senders',
    hiddenClueTitle: (l, lang, n) => `${n}-word clue without ${displayLetter(l, lang)}`,
    hiddenClueGeneric: 'Clue',
    reportedOn: 'Reported',
    hiddenOn: 'Hidden',
    senderN: (n) => `Sender ${n}`,
    unhide: 'Unhide',
    unhidden: 'Unhidden.',
    helpRulesTitle: 'Rules',
    helpRule1: 'Pick one of three words; a banned letter is dealt.',
    helpRule2: 'Describe the word in 8 words or fewer without using that letter. The secret word itself and its forms are banned too.',
    helpRule3: 'Letters and punctuation only: no digits, emoji or look-alike letters.',
    helpRule4: 'Your friend gets 3 tries. Plurals and a one-letter typo in longer words count.',
    helpRule5: 'In a rematch you swap roles, and your rival picks your banned letter.',
    helpScoreTitle: 'Points',
    helpScore1: 'Guesser: 3 points on try 1, 2 on try 2, 1 on try 3.',
    helpScore2: 'Clue writer: 9 minus the word count if the clue is guessed. Fewer words, more points.',
    helpScore3: 'An unsolved clue scores nothing; the score carries through rematches.',
    helpDailyTitle: 'Every day',
    helpDaily1: 'Word of the day: the same word and letter for everyone. Describe it and share; your friend guesses first, then tries a shorter clue.',
    helpDaily2: "Puzzle archive: solve our team's clues while you wait.",
    helpFairTitle: 'Fair and safe',
    helpFair1: 'The referee knows word endings: "cats", "c a t" and glued-together words are caught, while different words that merely look alike stay allowed.',
    helpFair2: 'A word filter runs while you write and when a link opens. Every clue has "Report" and "Hide clues from this sender".',
    helpFair3: "The creator pays, the player doesn't: solving any clue you receive is free.",
  },
};
