// Alıcı yolu metinleri (TR/EN): çöz, sonuç (alıcı ve kurucu), bildir ve gizle, çözme arşivi.
// Tahmin geri bildirimi, deste notu, puan ve açılış durumları C'nin aciklama.js'indedir.

import { letterSuffix, displayLetter } from '../turkce.js';

const enWords = (n) => (n === 1 ? '1 word' : `${n} words`);

export const SOLVE = {
  tr: {
    headingSomeone: (l, lang, n) => `Biri sana ${displayLetter(l, lang)} harfini hiç kullanmadan ${n} kelimeyle anlattı:`,
    headingRival: (l, lang, n) => `Rakibin sana ${displayLetter(l, lang)} harfini hiç kullanmadan ${n} kelimeyle anlattı:`,
    headingDaily: (l, lang, n) => `Biri sana günün sözcüğünü ${displayLetter(l, lang)} harfini hiç kullanmadan ${n} kelimeyle anlattı:`,
    headingArchive: (l, lang, n) => `${displayLetter(l, lang)} harfini hiç kullanmadan ${n} kelimeyle anlatıldı:`,
    archiveItemTitle: (no) => `Çözme arşivi #${no}`,
    theySolvedYours: (n) => `Rakibin senin anlatımını ${n}. hakta bildi.`,
    theyMissedYours: 'Rakibin senin anlatımını bilemedi.',
    yourGuess: 'Tahminin',
    guessButton: 'Tahmin et',
    triesLeftShort: (left, max) => `${max} haktan ${left} hak kaldı`,
    triedLabel: 'Denediklerin',
    giveUp: 'Pes et',
    giveUpTitle: 'Pes ediyor musun?',
    giveUpText: 'Gizli sözcük gösterilir ve tur biter.',
    keepGuessing: 'Denemeye devam',
    report: 'Bildir',
    hideSender: 'Gönderenden gelenleri gizle',
    reportTitle: 'Bu anlatımı bildir',
    reportIntro: 'Neden bildiriyorsun? Yalnız bulmaca ve seçtiğin neden gönderilir; bu anlatım bu cihazda hemen gizlenir.',
    reportReason: 'Neden',
    reportPick: 'Bir neden seç.',
    reportSend: 'Bildir',
    reportSending: 'Gönderiliyor…',
    reportOffline: 'Bağlantı yok; bu anlatım yine de bu cihazda gizlendi.',
    reportFailed: 'Bildirim gönderilemedi; bu anlatım yine de bu cihazda gizlendi.',
    ownNote: 'Bu anlatımı sen yazdın; arkadaşın böyle görecek.',
    archiveFoot: 'Bu anlatımı ekibimiz yazdı.',
    youGotIt: (n) => `Bildin: ${n}. hakta`,
    notThisTime: 'Bilemedin',
    theAnswerWas: 'Gizli sözcük',
    clueMeta: (l, lang, n) => `${letterSuffix(l, 'siz', lang)} ${n} kelime`,
    ownResultNote: 'Kendi anlatımını denedin; sonuç gönderilmez.',
    nowYouDescribeDaily: 'Şimdi sen anlat: günün sözcüğü',
    rematch: 'Rövanş: şimdi sen anlat',
    rematchBanned: (L) => `Sana ${L} yasak`,
    sendResult: 'Sonucu gönder',
    sendResultTitle: 'Sonucu gönder',
    nowYouDescribe: 'Şimdi sen birine anlat',
    nextArchive: (no) => `Sıradaki: #${no}`,
    cardTitle: 'Sonuç kartı',
    shareCard: 'Kartı paylaş',
    appLine: 'iOS uygulamasında desteler ve kart temaları var.',
    addToHome: 'Ana ekrana ekle',
    addToHomeHint: 'Tarayıcı menüsündeki «Ana ekrana ekle» ile bir dahaki sefere tek dokunuşla açılır.',
    yoursSolved: (n) => `Anlatımın ${n}. hakta bilindi`,
    yoursMissed: 'Anlatımın bilinemedi',
    creatorPoints: (mine, theirs) => `Senin puanın ${mine} · Arkadaşının puanı ${theirs} (az kelime, çok puan)`,
    unknownResult: 'Bu sonuç, bu cihazdan gönderilmemiş bir anlatıma ait.',
    sendNewClue: 'Yeni anlatım gönder',
    archiveTitle: 'Çözme arşivi',
    archiveIntro: 'Ekibimizin yazdığı anlatımlar. Arkadaş beklemeden çöz, kuralı oynayarak öğren.',
    archiveLang: 'Arşivin dili',
    archiveEmpty: 'Bu dilde henüz anlatım yok.',
    archiveNo: (no) => `Arşiv ${no}.`,
    archiveSolved: (n) => `${n}. hakta bildin`,
    archiveMissed: 'Bilemedin',
    archiveInProgress: 'Yarım kaldı',
    archiveProgress: (done, total) => `Ekibin anlatımları · ${done}/${total} çözüldü`,
  },
  en: {
    headingSomeone: (l, lang, n) => `Someone described this in ${enWords(n)} without the letter ${displayLetter(l, lang)}:`,
    headingRival: (l, lang, n) => `Your rival described this in ${enWords(n)} without the letter ${displayLetter(l, lang)}:`,
    headingDaily: (l, lang, n) => `Someone described the word of the day in ${enWords(n)} without the letter ${displayLetter(l, lang)}:`,
    headingArchive: (l, lang, n) => `Described in ${enWords(n)} without the letter ${displayLetter(l, lang)}:`,
    archiveItemTitle: (no) => `Puzzle archive #${no}`,
    theySolvedYours: (n) => `Your rival got yours on try ${n}.`,
    theyMissedYours: "Your rival couldn't get yours.",
    yourGuess: 'Your guess',
    guessButton: 'Guess',
    triesLeftShort: (left, max) => `${left} of ${max} tries left`,
    triedLabel: 'Your guesses',
    giveUp: 'Give up',
    giveUpTitle: 'Give up?',
    giveUpText: 'The secret word is shown and the round ends.',
    keepGuessing: 'Keep guessing',
    report: 'Report',
    hideSender: 'Hide clues from this sender',
    reportTitle: 'Report this clue',
    reportIntro: 'Why are you reporting it? Only the puzzle and the reason you pick are sent; the clue is hidden on this device right away.',
    reportReason: 'Reason',
    reportPick: 'Pick a reason.',
    reportSend: 'Report',
    reportSending: 'Sending…',
    reportOffline: 'No connection; the clue is still hidden on this device.',
    reportFailed: "The report couldn't be sent; the clue is still hidden on this device.",
    ownNote: 'You wrote this clue; this is what your friend sees.',
    archiveFoot: 'Our team wrote this clue.',
    youGotIt: (n) => `You got it: try ${n}`,
    notThisTime: 'Not this time',
    theAnswerWas: 'The secret word',
    clueMeta: (l, lang, n) => `${enWords(n)}, no ${displayLetter(l, lang)}`,
    ownResultNote: 'You tried your own clue; no result is sent.',
    nowYouDescribeDaily: 'Your turn: word of the day',
    rematch: 'Rematch: your turn to describe',
    rematchBanned: (L) => `${L} is banned for you`,
    sendResult: 'Send your result',
    sendResultTitle: 'Send your result',
    nowYouDescribe: 'Now describe one for a friend',
    nextArchive: (no) => `Next: #${no}`,
    cardTitle: 'Result card',
    shareCard: 'Share the card',
    appLine: 'The iOS app has more decks and card themes.',
    addToHome: 'Add to Home Screen',
    addToHomeHint: 'Use “Add to Home Screen” in your browser menu to open it in one tap next time.',
    yoursSolved: (n) => `Your clue was guessed on try ${n}`,
    yoursMissed: "Your clue wasn't guessed",
    creatorPoints: (mine, theirs) => `Your points ${mine} · Your friend's points ${theirs} (fewer words, more points)`,
    unknownResult: 'This result is for a clue that was not sent from this device.',
    sendNewClue: 'Send a new clue',
    archiveTitle: 'Puzzle archive',
    archiveIntro: 'Clues written by our team. Solve while you wait and learn the game as you play.',
    archiveLang: 'Archive language',
    archiveEmpty: 'No clues in this language yet.',
    archiveNo: (no) => `Archive ${no}.`,
    archiveSolved: (n) => `Got it on try ${n}`,
    archiveMissed: 'Missed',
    archiveInProgress: 'In progress',
    archiveProgress: (done, total) => `Clues by our team · ${done}/${total} solved`,
  },
};
