// Ortak arayüz metinleri (TR/EN). Harf eki ve büyük harf C'nin turkce.js'inden (yerel ayardan bağımsız İ/ı).

import { letterSuffix, displayLetter } from '../turkce.js';

const enWords = (n) => (n === 1 ? '1 word' : `${n} words`);

export const COMMON = {
  tr: {
    back: 'Geri',
    backHome: 'Ana ekran',
    close: 'Kapat',
    cancel: 'Vazgeç',
    done: 'Tamam',
    retry: 'Yeniden dene',
    reload: 'Yeniden yükle',
    reloadPage: 'Sayfayı yenile',
    screenFailed: 'Bu ekran açılamadı.',
    storeReset: 'Kayıtların okunamadı; oyun baştan başladı.',
    settings: 'Ayarlar',
    slogan: 'Bir harfi yasakla, anlat.',
    letterPhrase: (l, lang) => letterSuffix(l, 'siz', lang),
    bannedLetter: (L) => `Yasak harf ${L}`,
    attemptsUsed: (used, max) => `${max} haktan ${used} hak kullanıldı`,
    wordCount: (n) => `${n} kelime`,
    dayTag: (no) => `Günün sözcüğü #${no}`,
    dayTitle: (name, no) => `${name} #${no}`,
    scoreLabel: 'Skor',
    scoreValue: (me, them) => `Sen ${me} – Rakibin ${them}`,
    easy: 'Kolay',
    medium: 'Orta',
    hard: 'Zor',
    copy: 'Kopyala',
    copied: 'Kopyalandı.',
    copiedInstead: 'Açılamadı; mesaj kopyalandı.',
    otherApps: 'Diğer',
    whatsapp: 'WhatsApp',
    telegram: 'Telegram',
    xName: 'X',
    appMissing: (app) => `${app} bu cihazda yok.`,
    shareFailed: 'Paylaşılamadı.',
    cardSaved: 'Kart indirildi.',
    selectManually: 'Metni elle seç',
    selectManuallyHint: 'Kopyalanamadı. Metni seçip kopyala, sonra mesajına yapıştır.',
    messageText: 'Mesaj metni',
    locked: 'kilitli',
    langName_tr: 'Türkçe',
    langName_en: 'İngilizce',
    describeForFriend: 'Arkadaşına anlat',
    describeForFriendSub: 'Bir sözcük seç, yasak harfi kullanmadan anlat',
    writeYourOwn: 'Kendi anlatımını kur',
    openHidden: 'Gizlenenler',
    checkClock: 'Cihaz saatini denetle: tarih, oyunun başladığı günden önce görünüyor.',
  },
  en: {
    back: 'Back',
    backHome: 'Home',
    close: 'Close',
    cancel: 'Cancel',
    done: 'Done',
    retry: 'Try again',
    reload: 'Reload',
    reloadPage: 'Reload the page',
    screenFailed: "This screen couldn't open.",
    storeReset: "Your saved data couldn't be read, so the game started fresh.",
    settings: 'Settings',
    slogan: 'Ban a letter. Describe a word.',
    letterPhrase: (l, lang) => `no ${displayLetter(l, lang)}`,
    bannedLetter: (L) => `Banned letter ${L}`,
    attemptsUsed: (used, max) => `${used} of ${max} tries used`,
    wordCount: (n) => enWords(n),
    dayTag: (no) => `Word of the day #${no}`,
    dayTitle: (name, no) => `${name} #${no}`,
    scoreLabel: 'Score',
    scoreValue: (me, them) => `You ${me} – Rival ${them}`,
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    copy: 'Copy',
    copied: 'Copied.',
    copiedInstead: "Couldn't open it, so the message was copied.",
    otherApps: 'More',
    whatsapp: 'WhatsApp',
    telegram: 'Telegram',
    xName: 'X',
    appMissing: (app) => `${app} isn't on this device.`,
    shareFailed: "Couldn't share.",
    cardSaved: 'Card downloaded.',
    selectManually: 'Select the text',
    selectManuallyHint: "Copying didn't work. Select the text, copy it and paste it into your message.",
    messageText: 'Message text',
    locked: 'locked',
    langName_tr: 'Turkish',
    langName_en: 'English',
    describeForFriend: 'Describe one for a friend',
    describeForFriendSub: 'Pick a word, describe it without the banned letter',
    writeYourOwn: 'Write your own clue',
    openHidden: 'Hidden',
    checkClock: "Check your device clock: the date looks earlier than the game's first day.",
  },
};
