// Kurma yolu metinleri (TR/EN): deste, sözcük, yaz, gönder, gönderdiklerin, günün sözcüğü, ilk açılış örneği.
// Denetim uyarıları ve yönerge C'nin aciklama.js'indedir; paylaşım metni paylas.js'te.

import { letterSuffix, displayLetter } from '../turkce.js';

const enWords = (n) => (n === 1 ? '1 word' : `${n} words`);

export const CREATE = {
  tr: {
    createTitle: 'Arkadaşına anlat',
    pickDeck: 'Deste seç',
    deckFree: 'Ücretsiz',
    deckOwned: 'Alındı',
    deckAppOnly: 'Yalnız iOS uygulamasında',
    deckPrice: (price) => `Kilitli · ${price}`,
    priceLoading: 'fiyat yükleniyor',
    priceLoadingName: (name) => `${name}, fiyat yükleniyor`,
    storeUnavailableShort: "App Store'a ulaşılamadı",
    storeUnavailable: "App Store'a ulaşılamadı. Ücretsiz desteler çalışmaya devam eder.",
    deckSize: (n) => `${n} sözcük`,
    webDeckNote: 'Ücretli destelerle anlatmak yalnız iOS uygulamasında. Gelen anlatımları her yerde ücretsiz çözersin.',
    appOnlyDeck: 'Bu desteyle anlatmak yalnız iOS uygulamasında. Gelen anlatımları her yerde ücretsiz çözersin.',
    youSolvedTheirs: (n) => `Rakibinin anlatımını ${n}. hakta bildin. Sıra sende.`,
    youMissedTheirs: 'Rakibinin anlatımını bilemedin. Sıra sende.',
    pickWord: 'Bir sözcük seç',
    pickWordHint: 'Arkadaşın bu sözcüğü bilmeye çalışacak. Her sözcüğün yasak harfi yanında yazılı.',
    dealAgain: 'Başka üç sözcük',
    otherLangDeck: 'Bu destenin bulmacası kendi dilinde oynanır; kurallar o dile göre işler.',
    offerTitle: 'Aynı sözcükler dönmeye başladı mı? Yeni desteler',
    offerSee: 'Desteleri gör',
    offerNotNow: 'Şimdi değil',
    writeTitle: 'Anlat',
    deckTag: (name) => `Deste: ${name}`,
    secretWord: 'Gizli sözcük',
    yourClue: 'Anlatımın',
    previewPlaceholder: 'Yazdıkların burada denetlenir.',
    wordCounter: (n, max) => `${n}/${max} kelime`,
    charCounter: (n, max) => `${n}/${max} karakter`,
    canSend: 'Gönderilebilir',
    liveEmpty: 'Bir şey yaz.',
    liveOk: (n) => `${n} kelime, gönderilebilir`,
    liveIssues: (n, sentences) => `${n} sorun: ${sentences}`,
    issueCount: (n) => `${n} sorun`,
    issuesLabel: 'Uyarılar',
    rematchQuestion: 'Rövanşta rakibine hangi harfi yasaklıyorsun?',
    rematchHint: 'İsteğe bağlı. Seçmezsen rövanşta harf dağıtılır.',
    rematchNone: 'Dağıtılsın',
    moreLetters: 'Öteki harfler',
    fewerLetters: 'Daha az harf',
    createLink: 'Bağlantıyı oluştur',
    linkFailed: 'Bağlantı oluşturulamadı. Anlatımı biraz değiştirip yeniden dene.',
    sendTitle: 'Gönder',
    sendTitleNew: 'Bağlantın hazır',
    linkReady: 'Bulmaca bağlantının içinde; arkadaşın kurulum yapmadan tarayıcıda oynar.',
    messagePreview: 'Mesaj',
    messageTo: 'Arkadaşına gidecek mesaj',
    sendVia: 'Nereden gönderiyorsun?',
    sendHint: 'Anlatım mesajın içinde; cevap hiçbir yerde yok.',
    storyTitle: 'Hikâye kartı',
    storyHint: 'Instagram ya da WhatsApp Durum için dikey kart. Cevap kartta yok.',
    storyShare: 'Hikâye kartını paylaş',
    storyInstagram: 'Instagram hikâyesi',
    storyWhatsapp: 'WhatsApp Durum',
    saveImage: 'Görseli kaydet',
    seeAsFriend: 'Arkadaşın böyle görecek',
    openHere: 'Bağlantıyı bu cihazda aç',
    newClue: 'Yeni anlatım',
    sentTitle: 'Gönderdiklerin',
    sentEmpty: 'Henüz kimseye anlatmadın. İlkini yaz.',
    sentAll: (n) => `Tümü (${n})`,
    statusWaiting: 'Sonuç bekleniyor',
    statusSolved: (n) => `${n}. hakta bilindi`,
    statusMissed: 'Bilinemedi',
    dailyTitle: 'Günün sözcüğü',
    dailyHeading: (no) => `Günün sözcüğü #${no}`,
    dailyLetter: (l, lang) => `${letterSuffix(l, 'siz', lang)} anlat`,
    dailyDone: (n) => `Bugün ${n} kelimeyle anlattın`,
    dailyDonePast: (n) => `${n} kelimeyle anlattın`,
    dailyReveal: 'Sözcüğü gör ve anlat',
    dailyRevealShort: 'Sözcüğü gör',
    dailyShareAgain: 'Yeniden paylaş',
    dailyExplain: 'Bugün herkese aynı sözcük ve aynı yasak harf. Sözcük, sen dokunana dek gizli kalır; arkadaşının bağlantısı bozulmasın.',
    dailyShareTitle: 'Arkadaşlarına gönder',
    dailyShareHint: 'Önce onlar bilsin, sonra daha kısasını yazsınlar.',
    dailyTomorrow: 'Yarın yeni bir sözcük var.',
    streakDays: (n) => `Seri: ${n} gün`,
    pastDays: 'Geçmiş günler',
    pastDaysLocked: (name) => `Geçmiş günlerin sözcükleriyle anlatmak ${name} Hepsi ile açılır. Bugünün sözcüğü her zaman ücretsiz.`,
    pastDaysEmpty: 'Henüz geçmiş gün yok.',
    dayDone: 'Anlattın',
    exampleTitle: 'Böyle oynanır',
    exampleSetup: (word, l, lang) => `Gizli sözcük «${word}», yasak harf ${displayLetter(l, lang)}:`,
    exampleTry: (w) => `Sen dene: «${w}» yaz`,
    exampleHint: 'Yasak harfi kullanan sözcük kırmızı yanar ve ⚠ alır.',
    exampleOk: 'Bu anlatım geçerli.',
    gotIt: 'Anladım',
  },
  en: {
    createTitle: 'Describe one for a friend',
    pickDeck: 'Pick a deck',
    deckFree: 'Free',
    deckOwned: 'Purchased',
    deckAppOnly: 'In the iOS app only',
    deckPrice: (price) => `Locked · ${price}`,
    priceLoading: 'loading price',
    priceLoadingName: (name) => `${name}, loading price`,
    storeUnavailableShort: "Couldn't reach the App Store",
    storeUnavailable: "Couldn't reach the App Store. Free decks still work.",
    deckSize: (n) => (n === 1 ? '1 word' : `${n} words`),
    webDeckNote: 'Writing with paid decks is in the iOS app. You can solve clues from any deck for free, anywhere.',
    appOnlyDeck: 'Writing with this deck is in the iOS app. You can solve clues from any deck for free, anywhere.',
    youSolvedTheirs: (n) => `You got your rival's clue on try ${n}. Your turn.`,
    youMissedTheirs: "You missed your rival's clue. Your turn.",
    pickWord: 'Pick a word',
    pickWordHint: 'Your friend will try to guess it. Each word shows its banned letter.',
    dealAgain: 'Three other words',
    otherLangDeck: "Clues from this deck are played in the deck's language, with that language's rules.",
    offerTitle: 'Seeing the same words again? New decks',
    offerSee: 'See decks',
    offerNotNow: 'Not now',
    writeTitle: 'Describe',
    deckTag: (name) => `Deck: ${name}`,
    secretWord: 'Secret word',
    yourClue: 'Your clue',
    previewPlaceholder: 'What you type is checked here.',
    wordCounter: (n, max) => `${n}/${max} words`,
    charCounter: (n, max) => `${n}/${max} characters`,
    canSend: 'Ready to send',
    liveEmpty: 'Write something.',
    liveOk: (n) => `${enWords(n)}, ready to send`,
    liveIssues: (n, sentences) => `${n === 1 ? '1 problem' : `${n} problems`}: ${sentences}`,
    issueCount: (n) => (n === 1 ? '1 problem' : `${n} problems`),
    issuesLabel: 'Warnings',
    rematchQuestion: "Which letter do you ban for your rival's rematch?",
    rematchHint: 'Optional. If you skip it, a letter is dealt in the rematch.',
    rematchNone: 'Deal one',
    moreLetters: 'More letters',
    fewerLetters: 'Fewer letters',
    createLink: 'Create link',
    linkFailed: "Couldn't create the link. Change the clue a little and try again.",
    sendTitle: 'Send',
    sendTitleNew: 'Your link is ready',
    linkReady: 'The puzzle lives in the link; your friend plays in the browser, nothing to install.',
    messagePreview: 'Message',
    messageTo: 'What your friend gets',
    sendVia: 'Send it with',
    sendHint: 'The clue is in the message; the answer is nowhere in it.',
    storyTitle: 'Story card',
    storyHint: 'A tall card for an Instagram story or WhatsApp Status. The answer is not on it.',
    storyShare: 'Share story card',
    storyInstagram: 'Instagram story',
    storyWhatsapp: 'WhatsApp Status',
    saveImage: 'Save image',
    seeAsFriend: 'See what your friend sees',
    openHere: 'Open the link on this device',
    newClue: 'New clue',
    sentTitle: 'Sent',
    sentEmpty: "You haven't described anything yet. Write your first.",
    sentAll: (n) => `All (${n})`,
    statusWaiting: 'Waiting for the result',
    statusSolved: (n) => `Guessed on try ${n}`,
    statusMissed: 'Not guessed',
    dailyTitle: 'Word of the day',
    dailyHeading: (no) => `Word of the day #${no}`,
    dailyLetter: (l, lang) => `Describe it without the letter ${displayLetter(l, lang)}`,
    dailyDone: (n) => `You described today's word in ${enWords(n)}`,
    dailyDonePast: (n) => `You described it in ${enWords(n)}`,
    dailyReveal: 'Reveal and describe',
    dailyRevealShort: 'Reveal the word',
    dailyShareAgain: 'Share again',
    dailyExplain: "Everyone gets the same word and banned letter today. The word stays hidden until you tap, so a friend's link isn't spoiled.",
    dailyShareTitle: 'Send it to friends',
    dailyShareHint: 'They guess first, then try a shorter clue.',
    dailyTomorrow: "There's a new word tomorrow.",
    streakDays: (n) => `Streak: ${n === 1 ? '1 day' : `${n} days`}`,
    pastDays: 'Past days',
    pastDaysLocked: (name) => `Writing with past days' words comes with ${name} All. Today's word is always free.`,
    pastDaysEmpty: 'No past days yet.',
    dayDone: 'Described',
    exampleTitle: 'How it works',
    exampleSetup: (word, l, lang) => `Secret word «${word}», banned letter ${displayLetter(l, lang)}:`,
    exampleTry: (w) => `Your turn: type «${w}»`,
    exampleHint: 'A word with the banned letter lights up red and gets a ⚠.',
    exampleOk: 'This clue works.',
    gotIt: 'Got it',
  },
};
