// Basics deck (EN, free; Word of the day pool). Format: docs/icerik-bicimi.md §3. Curated by C2 (tools/icerik/KAYNAKLAR.md).
// Record: [word, Turkish translation, difficulty 1–3] or
// { soz, ceviri, zorluk, harf, kokler, serbest, esler, gosterim, gunluk }.
// American spelling. The order is the Word of the day pool order (§7): after release records are never removed or
// reordered; new words go to the end with `gunluk: false`.
//
// - Compounds and plural-only nouns list their meaningful stem (4+ letters) in `kokler`: "popcorn" → "corn",
//   "glasses" → "glass".
// - `serbest` frees unrelated words the checker would catch and that come up naturally in a clue: the stem found
//   inside longer words ("king" → "making"), e-drop stems ("shoe" → "short"), doubled stems ("car" → "carry").
export const SOZCUKLER = Object.freeze([
  ['cat', 'kedi', 1], ['dog', 'köpek', 1], ['book', 'kitap', 1], ['tree', 'ağaç', 1], ['sea', 'deniz', 1],
  ['sun', 'güneş', 1], ['cloud', 'bulut', 1], ['pencil', 'kurşun kalem', 1],
  { soz: 'table', ceviri: 'masa', zorluk: 1, serbest: ['vegetable'] },
  ['chair', 'sandalye', 1],
  ['phone', 'telefon', 1],
  { soz: 'car', ceviri: 'araba', zorluk: 1, serbest: ['carry', 'carries', 'carried', 'card'] },
  { soz: 'airplane', ceviri: 'uçak', zorluk: 1, kokler: ['plane'] },
  ['ship', 'gemi', 1], ['train', 'tren', 1],
  ['bicycle', 'bisiklet', 1], ['umbrella', 'şemsiye', 2], ['mirror', 'ayna', 2], ['clock', 'saat', 1], ['key', 'anahtar', 1],
  ['door', 'kapı', 1], ['window', 'pencere', 1], ['bed', 'yatak', 1], ['pillow', 'yastık', 2], ['blanket', 'battaniye', 2],
  ['tea', 'çay', 1], ['coffee', 'kahve', 1], ['bread', 'ekmek', 1], ['cheese', 'peynir', 1], ['olive', 'zeytin', 2],
  ['apple', 'elma', 1], ['banana', 'muz', 1],
  { soz: 'strawberry', ceviri: 'çilek', zorluk: 1, kokler: ['berry'] },
  { soz: 'watermelon', ceviri: 'karpuz', zorluk: 1, kokler: ['water', 'melon'], gunluk: false },
  { soz: 'ice cream', ceviri: 'dondurma', zorluk: 1, gunluk: false },
  ['cake', 'pasta', 1], ['wedding', 'düğün', 2], ['school', 'okul', 1], ['teacher', 'öğretmen', 1], ['doctor', 'doktor', 1],
  ['hospital', 'hastane', 1], ['guitar', 'gitar', 2], ['piano', 'piyano', 2],
  { soz: 'snow', ceviri: 'kar', zorluk: 1, gunluk: false },
  { soz: 'rain', ceviri: 'yağmur', zorluk: 1 },
  { soz: 'wind', ceviri: 'rüzgar', zorluk: 1, serbest: ['window', 'winding'] },
  ['mountain', 'dağ', 1], ['forest', 'orman', 1], ['desert', 'çöl', 2], ['island', 'ada', 1],
  ['bridge', 'köprü', 1], ['balloon', 'balon', 1], ['candle', 'mum', 1], ['gift', 'hediye', 1], ['photo', 'fotoğraf', 2],
  { soz: 'glasses', ceviri: 'gözlük', zorluk: 1, kokler: ['glass'] },
  { soz: 'shoe', ceviri: 'ayakkabı', zorluk: 1 },
  ['bag', 'çanta', 1], ['nose', 'burun', 1], ['city', 'şehir', 2],
  { soz: 'ear', ceviri: 'kulak', zorluk: 1, serbest: ['early'] },
  ['tooth', 'diş', 1],
  { soz: 'hair', ceviri: 'saç', zorluk: 1 },
  ['heart', 'kalp', 2], ['star', 'yıldız', 1],
  { soz: 'rainbow', ceviri: 'gökkuşağı', zorluk: 2, kokler: ['rain'] },
  ['lightning', 'şimşek', 2], ['volcano', 'yanardağ', 2], ['river', 'nehir', 2],
  ['lake', 'göl', 1],
  { soz: 'beach', ceviri: 'plaj', zorluk: 1, gunluk: false },
  { soz: 'sand', ceviri: 'kum', zorluk: 1, serbest: ['thousand'] },
  ['stone', 'taş', 1], ['flower', 'çiçek', 1],
  ['rose', 'gül', 1], ['tulip', 'lale', 2], ['daisy', 'papatya', 2], ['butterfly', 'kelebek', 1], ['bee', 'arı', 1],
  ['ant', 'karınca', 1], ['spider', 'örümcek', 1], ['fish', 'balık', 1], ['bird', 'kuş', 1], ['chicken', 'tavuk', 1],
  ['cow', 'inek', 1], ['horse', 'at', 1], ['sheep', 'koyun', 1], ['goat', 'keçi', 1],
  { soz: 'lion', ceviri: 'aslan', zorluk: 1, serbest: ['million'] },
  ['tiger', 'kaplan', 1], ['elephant', 'fil', 1], ['giraffe', 'zürafa', 1], ['monkey', 'maymun', 1],
  { soz: 'bear', ceviri: 'ayı', zorluk: 1, serbest: ['beard', 'bearing'] },
  ['rabbit', 'tavşan', 1], ['turtle', 'kaplumbağa', 1], ['snake', 'yılan', 1], ['crocodile', 'timsah', 2], ['penguin', 'penguen', 1],
  ['owl', 'baykuş', 2], ['eagle', 'kartal', 2], ['rooster', 'horoz', 2], ['mouse', 'fare', 1], ['squirrel', 'sincap', 2],
  ['hedgehog', 'kirpi', 2], ['television', 'televizyon', 1], ['computer', 'bilgisayar', 1], ['lamp', 'lamba', 1], ['carpet', 'halı', 2],
  ['curtain', 'perde', 2],
  { soz: 'stairs', ceviri: 'merdiven', zorluk: 2, kokler: ['stair'] },
  ['elevator', 'asansör', 2], ['roof', 'çatı', 2], ['garden', 'bahçe', 1],
  ['tent', 'çadır', 2], ['map', 'harita', 2], ['compass', 'pusula', 3], ['envelope', 'zarf', 2],
  { soz: 'newspaper', ceviri: 'gazete', zorluk: 2, kokler: ['paper', 'news'] },
  ['dictionary', 'sözlük', 2],
  { soz: 'notebook', ceviri: 'defter', zorluk: 1, kokler: ['book'] },
  ['eraser', 'silgi', 1], ['ruler', 'cetvel', 2], ['scissors', 'makas', 1],
  ['needle', 'iğne', 2], ['button', 'düğme', 2], ['zipper', 'fermuar', 3], ['hat', 'şapka', 1],
  { soz: 'glove', ceviri: 'eldiven', zorluk: 2, gunluk: false },
  { soz: 'scarf', ceviri: 'atkı', zorluk: 2, gunluk: false },
  ['jacket', 'ceket', 2], ['pajamas', 'pijama', 2],
  { soz: 'slipper', ceviri: 'terlik', zorluk: 2, serbest: ['slippery'] },
  ['sock', 'çorap', 1],
  ['belt', 'kemer', 2], ['wallet', 'cüzdan', 2], ['money', 'para', 1], ['ticket', 'bilet', 2], ['suitcase', 'valiz', 2],
  ['passport', 'pasaport', 2],
  { soz: 'bus', ceviri: 'otobüs', zorluk: 1, serbest: ['busy'] },
  ['taxi', 'taksi', 1], ['subway', 'metro', 2], ['rocket', 'roket', 2],
  ['submarine', 'denizaltı', 2], ['helicopter', 'helikopter', 2], ['tractor', 'traktör', 2], ['ambulance', 'ambulans', 2], ['cinema', 'sinema', 2],
  ['museum', 'müze', 2], ['library', 'kütüphane', 2], ['pharmacy', 'eczane', 2], ['toy', 'oyuncak', 1], ['baby', 'bebek', 1],
  { soz: 'ball', ceviri: 'top', zorluk: 1, serbest: ['balloon'] },
  ['chess', 'satranç', 2],
  { soz: 'dice', ceviri: 'zar', zorluk: 2 },
  ['puzzle', 'bulmaca', 2], ['castle', 'kale', 2],
  {
    soz: 'king', ceviri: 'kral', zorluk: 1,
  },
  ['queen', 'kraliçe', 1], ['robot', 'robot', 1], ['planet', 'gezegen', 2], ['telescope', 'teleskop', 3],
  ['magnet', 'mıknatıs', 3], ['battery', 'pil', 2], ['light bulb', 'ampul', 2], ['camera', 'kamera', 2], ['microphone', 'mikrofon', 2],
  { soz: 'headphones', ceviri: 'kulaklık', zorluk: 2, kokler: ['headphone'] },
  ['radio', 'radyo', 2], ['drum', 'davul', 2], ['violin', 'keman', 2], ['bell', 'zil', 2],
  ['calendar', 'takvim', 2],
  { soz: 'birthday', ceviri: 'doğum günü', zorluk: 1, kokler: ['birth'] },
  { soz: 'snowman', ceviri: 'kardan adam', zorluk: 1, kokler: ['snow'], gunluk: false },
  ['breakfast', 'kahvaltı', 1], ['soup', 'çorba', 1],
  { soz: 'rice', ceviri: 'pirinç', zorluk: 1 },
  ['pizza', 'pizza', 1], ['honey', 'bal', 1], ['egg', 'yumurta', 1], ['milk', 'süt', 1],
  ['lemon', 'limon', 1], ['orange', 'portakal', 1], ['grape', 'üzüm', 1], ['pear', 'armut', 1], ['cherry', 'kiraz', 1],
  ['tomato', 'domates', 1], ['carrot', 'havuç', 1], ['potato', 'patates', 1], ['onion', 'soğan', 1],
  { soz: 'corn', ceviri: 'mısır', zorluk: 2, serbest: ['corner'] },
  ['walnut', 'ceviz', 2], ['finger', 'parmak', 1], ['foot', 'ayak', 1], ['elbow', 'dirsek', 2], ['beard', 'sakal', 2],
  ['hot dog', 'sosisli', 2],
  { soz: 'teddy bear', ceviri: 'oyuncak ayı', zorluk: 1, serbest: ['beard', 'bearing'] },
  { soz: 'lighthouse', ceviri: 'deniz feneri', zorluk: 2, kokler: ['light', 'house'] },
  { soz: 'kite', ceviri: 'uçurtma', zorluk: 1, serbest: ['kitten'] },
  ['ladder', 'el merdiveni', 2],

  // Body
  ['eye', 'göz', 1],
  { soz: 'hand', ceviri: 'el', zorluk: 1, serbest: ['handle', 'handsome'] },
  ['mouth', 'ağız', 1], ['tongue', 'dil', 2], ['mustache', 'bıyık', 2],
  ['chin', 'çene', 2], ['neck', 'boyun', 2], ['knee', 'diz', 2], ['skeleton', 'iskelet', 2], ['bone', 'kemik', 2],
  ['brain', 'beyin', 2], ['dimple', 'gamze', 3],
  { soz: 'fingerprint', ceviri: 'parmak izi', zorluk: 3, kokler: ['finger', 'print'] },
  ['sneeze', 'hapşırık', 3], ['hiccup', 'hıçkırık', 3],
  ['snore', 'horultu', 3], ['whisper', 'fısıltı', 3],

  // Nature and sky
  ['moon', 'ay', 1], ['sky', 'gökyüzü', 1], ['wave', 'dalga', 1],
  { soz: 'rock', ceviri: 'kaya', zorluk: 1, serbest: ['rocket'] },
  ['leaf', 'yaprak', 1],
  { soz: 'fire', ceviri: 'ateş', zorluk: 1 },
  ['ice', 'buz', 1], ['water', 'su', 1], ['mud', 'çamur', 2], ['cactus', 'kaktüs', 2],
  ['fog', 'sis', 2], ['storm', 'fırtına', 2],
  { soz: 'waterfall', ceviri: 'şelale', zorluk: 2, kokler: ['water'] },
  ['cave', 'mağara', 2], ['hill', 'tepe', 2],
  { soz: 'sunflower', ceviri: 'ayçiçeği', zorluk: 2, kokler: ['flower'] },
  ['smoke', 'duman', 2], ['thunder', 'gök gürültüsü', 2], ['sunset', 'gün batımı', 2],
  { soz: 'seashell', ceviri: 'deniz kabuğu', zorluk: 2, kokler: ['shell'] },
  ['diamond', 'elmas', 2], ['gold', 'altın', 2], ['shadow', 'gölge', 2], ['comet', 'kuyruklu yıldız', 3], ['meteor', 'göktaşı', 3],
  { soz: 'black hole', ceviri: 'kara delik', zorluk: 3 },
  ['satellite', 'uydu', 3], ['eclipse', 'tutulma', 3], ['dawn', 'şafak', 3], ['valley', 'vadi', 3],
  ['glacier', 'buzul', 3],
  { soz: 'avalanche', ceviri: 'çığ', zorluk: 3, gunluk: false },
  { soz: 'frost', ceviri: 'kırağı', zorluk: 3, gunluk: false },
  { soz: 'whirlpool', ceviri: 'girdap', zorluk: 3, kokler: ['whirl'] },
  ['mirage', 'serap', 3],
  ['echo', 'yankı', 3], ['pine cone', 'kozalak', 3], ['ivy', 'sarmaşık', 3], ['willow', 'söğüt', 3], ['orchid', 'orkide', 3],
  ['cliff', 'uçurum', 3],

  // Animals
  ['donkey', 'eşek', 1], ['camel', 'deve', 1], ['wolf', 'kurt', 1], ['fox', 'tilki', 1], ['deer', 'geyik', 1],
  ['zebra', 'zebra', 1], ['octopus', 'ahtapot', 1], ['dolphin', 'yunus', 1], ['whale', 'balina', 1], ['shark', 'köpek balığı', 1],
  ['crab', 'yengeç', 1], ['frog', 'kurbağa', 1], ['duck', 'ördek', 1], ['kitten', 'yavru kedi', 1], ['lamb', 'kuzu', 2],
  ['mosquito', 'sivrisinek', 2], ['pigeon', 'güvercin', 2],
  { soz: 'seagull', ceviri: 'martı', zorluk: 2, kokler: ['gull'] },
  ['rhino', 'gergedan', 2], ['hippo', 'hipopotam', 2],
  ['gorilla', 'goril', 2],
  { soz: 'jellyfish', ceviri: 'denizanası', zorluk: 2, kokler: ['jelly'] },
  ['lizard', 'kertenkele', 2], ['swan', 'kuğu', 2], ['goose', 'kaz', 2],
  ['ostrich', 'devekuşu', 2], ['peacock', 'tavus kuşu', 2], ['parrot', 'papağan', 2], ['beaver', 'kunduz', 3], ['mole', 'köstebek', 3],

  // Places
  ['house', 'ev', 1], ['room', 'oda', 1], ['wall', 'duvar', 1], ['park', 'park', 1], ['farm', 'çiftlik', 1],
  ['zoo', 'hayvanat bahçesi', 1],
  { soz: 'supermarket', ceviri: 'market', zorluk: 2, kokler: ['market'] },
  ['village', 'köy', 1],
  { soz: 'classroom', ceviri: 'sınıf', zorluk: 2, kokler: ['class'] },
  ['ceiling', 'tavan', 2],
  { soz: 'bakery', ceviri: 'fırın', zorluk: 2, kokler: ['bake'] },
  ['airport', 'havalimanı', 2], ['aquarium', 'akvaryum', 2], ['traffic light', 'trafik ışığı', 2], ['palace', 'saray', 2],
  ['tower', 'kule', 2], ['fountain', 'çeşme', 2], ['statue', 'heykel', 2], ['pyramid', 'piramit', 2],
  { soz: 'skyscraper', ceviri: 'gökdelen', zorluk: 2, kokler: ['scraper'] },
  ['igloo', 'iglo', 2], ['hut', 'kulübe', 3],
  { soz: 'maze', ceviri: 'labirent', zorluk: 3 },

  // Getting around
  ['truck', 'kamyon', 1], ['wheel', 'tekerlek', 1],
  { soz: 'motorcycle', ceviri: 'motosiklet', zorluk: 2, kokler: ['motor'] },
  ['ferry', 'vapur', 2],
  { soz: 'sailboat', ceviri: 'yelkenli', zorluk: 2, kokler: ['sail', 'boat'] },
  ['parachute', 'paraşüt', 2],
  { soz: 'fire truck', ceviri: 'itfaiye', zorluk: 2 }, ['blimp', 'zeplin', 3], ['space shuttle', 'uzay mekiği', 3],

  // Home and things
  ['hammer', 'çekiç', 1], ['broom', 'süpürge', 1], ['soap', 'sabun', 1],
  { soz: 'toothbrush', ceviri: 'diş fırçası', zorluk: 1, kokler: ['tooth', 'brush'] },
  ['towel', 'havlu', 1],
  ['bottle', 'şişe', 1], ['box', 'kutu', 1], ['basket', 'sepet', 1], ['sofa', 'kanepe', 1], ['bucket', 'kova', 1],
  ['lock', 'kilit', 1], ['shampoo', 'şampuan', 1], ['comb', 'tarak', 2], ['shower', 'duş', 1], ['piggy bank', 'kumbara', 2],
  ['drawer', 'çekmece', 2], ['vase', 'vazo', 2],
  { soz: 'toothpaste', ceviri: 'diş macunu', zorluk: 2, kokler: ['tooth', 'paste'] },
  { soz: 'bathtub', ceviri: 'küvet', zorluk: 2, kokler: ['bath'] },
  { soz: 'fireplace', ceviri: 'şömine', zorluk: 2, kokler: ['fire'] },
  ['chimney', 'baca', 2], ['fence', 'çit', 2],
  { soz: 'scarecrow', ceviri: 'korkuluk', zorluk: 2, kokler: ['scare'] },
  { soz: 'windmill', ceviri: 'yel değirmeni', zorluk: 2, kokler: ['wind'], serbest: ['window', 'winding'] },
  { soz: 'flashlight', ceviri: 'el feneri', zorluk: 2, kokler: ['flash', 'light'] },
  { soz: 'mailbox', ceviri: 'posta kutusu', zorluk: 2, kokler: ['mail'] },
  { soz: 'fireworks', ceviri: 'havai fişek', zorluk: 2, kokler: ['fire', 'firework'] },
  { soz: 'campfire', ceviri: 'kamp ateşi', zorluk: 2, kokler: ['camp', 'fire'] },
  ['alarm clock', 'çalar saat', 2],
  { soz: 'hourglass', ceviri: 'kum saati', zorluk: 3, kokler: ['hour', 'glass'] },
  ['microscope', 'mikroskop', 3], ['lens', 'mercek', 3], ['prism', 'prizma', 3], ['pendulum', 'sarkaç', 3],
  { soz: 'lever', ceviri: 'kaldıraç', zorluk: 3 },
  ['pulley', 'makara', 3], ['drill', 'matkap', 3], ['pliers', 'pense', 3], ['rake', 'tırmık', 3],
  { soz: 'stapler', ceviri: 'zımba', zorluk: 3, kokler: ['staple'] },
  ['accordion', 'akordeon', 3], ['harmonica', 'mızıka', 3], ['pottery', 'çömlek', 3],
  { soz: 'typewriter', ceviri: 'daktilo', zorluk: 3, kokler: ['type', 'writer'] },
  ['thimble', 'yüksük', 3],
  { soz: 'knitting', ceviri: 'örgü', zorluk: 3, kokler: ['knit'] },
  ['hammock', 'hamak', 3],
  { soz: 'deck chair', ceviri: 'şezlong', zorluk: 3, gunluk: false },

  // Clothes
  ['sweater', 'kazak', 1], ['shirt', 'gömlek', 1], ['dress', 'elbise', 1], ['coat', 'palto', 1], ['skirt', 'etek', 1],
  { soz: 'shorts', ceviri: 'şort', zorluk: 2, kokler: ['short'] },
  ['boot', 'çizme', 2],
  { soz: 'necklace', ceviri: 'kolye', zorluk: 2, kokler: ['neck'] },
  ['bow tie', 'papyon', 3],

  // People and everyday life
  ['grandma', 'büyükanne', 1], ['friend', 'arkadaş', 1], ['night', 'gece', 1], ['tail', 'kuyruk', 1], ['song', 'şarkı', 1],
  ['nest', 'yuva', 1], ['neighbor', 'komşu', 2], ['poem', 'şiir', 3], ['dream', 'rüya', 3],
  { soz: 'curiosity', ceviri: 'merak', zorluk: 3, kokler: ['curious'], gunluk: false },
  { soz: 'silence', ceviri: 'sessizlik', zorluk: 3, kokler: ['silent'], gunluk: false },
  { soz: 'luck', ceviri: 'şans', zorluk: 3, gunluk: false },
  { soz: 'laziness', ceviri: 'tembellik', zorluk: 3, kokler: ['lazy'], gunluk: false },

  // Food
  ['sandwich', 'sandviç', 1],
  { soz: 'cookie', ceviri: 'kurabiye', zorluk: 1 },
  ['chocolate', 'çikolata', 1],
  { soz: 'popcorn', ceviri: 'patlamış mısır', zorluk: 1, kokler: ['corn'] },
  ['candy', 'şeker', 1],
  { soz: 'pancake', ceviri: 'pankek', zorluk: 1, kokler: ['cake'] },
]);
