// Temel deste (TR, ücretsiz; günün sözcüğü havuzu). Biçim: docs/icerik-bicimi.md §3.
// Kayıt: [sözcük, İngilizce karşılığı, zorluk 1–3] ya da
// { soz, ceviri, zorluk, harf, kokler, serbest, esler, gosterim, gunluk }.
// Seçki C2'nindir (tools/icerik/KAYNAKLAR.md). Sıra günün sözcüğü havuzunun sırasıdır (§7): yayından sonra
// kayıt silinmez, sırası ve harf önerisi değişmez; yeni sözcük sona `gunluk: false` ile eklenir.
//
// İçerik kuralları (web/tests/icerik-deste.test.js sınar):
// - Bitişik birleşik ve türemiş sözcükte anlamlı kök `kokler`e yazılır: "denizanası" → "deniz"; bitişik birleşiğin
//   3 harflik parçası da ("gökkuşağı" → "gök"). Fiilden türemiş cevapta fiil kökü: uzunsa düz ("dondurma" →
//   "dondur"), kısaysa sonu tireyle ("uyku" → "uyu-"); mastarı motor kendisi yakalar ("dondurmak").
// - Kökü kısa türemişte `harf` önerisi kökün harflerinden seçilir: "gözlük" → G, Ö, Z
//   (dağıtılan harf "göz"ü de kullanılmaz kılar).
// - Eşit sıklıkta ikinci ad `esler`e yazılır ("havalimanı" → "havaalanı"): tahminde doğru, anlatımda yasak.
// - `serbest` yalnız anlatırken doğal olarak geçebilecek ilgisiz sözcükleri açar ("simit" → "şimdi").
// - Günün sözcüğü havuzunda mevsime bağlı sözcük (kar, karpuz, plaj, atkı…) ve soyut duygu ya da huy adı yoktur.
export const SOZCUKLER = Object.freeze([
  ['kedi', 'cat', 1], ['köpek', 'dog', 1], ['kitap', 'book', 1], ['ağaç', 'tree', 1], ['deniz', 'sea', 1],
  ['güneş', 'sun', 1],
  { soz: 'bulut', ceviri: 'cloud', zorluk: 1 },
  ['kalem', 'pen', 1], ['masa', 'table', 1], ['sandalye', 'chair', 1],
  ['telefon', 'phone', 1], ['araba', 'car', 1], ['uçak', 'airplane', 1], ['gemi', 'ship', 1], ['tren', 'train', 1],
  ['bisiklet', 'bicycle', 1], ['şemsiye', 'umbrella', 1], ['ayna', 'mirror', 1], ['saat', 'clock', 1], ['anahtar', 'key', 1],
  ['kapı', 'door', 1], ['pencere', 'window', 1], ['yatak', 'bed', 1], ['yastık', 'pillow', 2], ['battaniye', 'blanket', 2],
  ['çay', 'tea', 1], ['kahve', 'coffee', 1],
  { soz: 'ekmek', ceviri: 'bread', zorluk: 1 },
  ['peynir', 'cheese', 1], ['zeytin', 'olive', 1],
  ['elma', 'apple', 1], ['muz', 'banana', 1], ['çilek', 'strawberry', 1],
  { soz: 'karpuz', ceviri: 'watermelon', zorluk: 1, gunluk: false },
  { soz: 'dondurma', ceviri: 'ice cream', zorluk: 1, kokler: ['dondur'], gunluk: false },
  ['pasta', 'cake', 1], ['düğün', 'wedding', 2], ['okul', 'school', 1], ['öğretmen', 'teacher', 1], ['doktor', 'doctor', 1],
  { soz: 'hastane', ceviri: 'hospital', zorluk: 1, kokler: ['hasta'] },
  ['gitar', 'guitar', 2],
  { soz: 'piyano', ceviri: 'piano', zorluk: 2, kokler: ['piyan'] },
  { soz: 'kar', ceviri: 'snow', zorluk: 1, gunluk: false },
  ['yağmur', 'rain', 1],
  ['rüzgar', 'wind', 1], ['dağ', 'mountain', 1], ['orman', 'forest', 1], ['çöl', 'desert', 2], ['ada', 'island', 1],
  ['köprü', 'bridge', 1], ['balon', 'balloon', 1], ['mum', 'candle', 1], ['hediye', 'gift', 1], ['fotoğraf', 'photo', 1],
  { soz: 'gözlük', ceviri: 'glasses', zorluk: 1, harf: ['G', 'Ö', 'Z'] },
  { soz: 'ayakkabı', ceviri: 'shoe', zorluk: 1, kokler: ['ayak'] },
  ['çanta', 'bag', 1], ['burun', 'nose', 1], ['şehir', 'city', 2],
  ['kulak', 'ear', 1], ['diş', 'tooth', 1], ['saç', 'hair', 1], ['kalp', 'heart', 2], ['yıldız', 'star', 1],
  { soz: 'gökkuşağı', ceviri: 'rainbow', zorluk: 2, kokler: ['gök', 'kuşak'] },
  { soz: 'şimşek', ceviri: 'lightning', zorluk: 2, esler: ['yıldırım'] },
  ['yanardağ', 'volcano', 2], ['nehir', 'river', 2], ['göl', 'lake', 1],
  { soz: 'plaj', ceviri: 'beach', zorluk: 1, gunluk: false },
  ['kum', 'sand', 1], ['taş', 'stone', 1], ['çiçek', 'flower', 1], ['gül', 'rose', 1],
  ['lale', 'tulip', 2], ['papatya', 'daisy', 2], ['kelebek', 'butterfly', 1], ['arı', 'bee', 1], ['karınca', 'ant', 1],
  ['örümcek', 'spider', 1],
  { soz: 'balık', ceviri: 'fish', zorluk: 1, serbest: ['kalabalık'] },
  { soz: 'kuş', ceviri: 'bird', zorluk: 1 },
  ['tavuk', 'chicken', 1],
  { soz: 'inek', ceviri: 'cow', zorluk: 1, serbest: ['sivrisinek'] },
  ['koyun', 'sheep', 1], ['keçi', 'goat', 1], ['aslan', 'lion', 1], ['kaplan', 'tiger', 1], ['fil', 'elephant', 1],
  ['zürafa', 'giraffe', 1], ['maymun', 'monkey', 1], ['ayı', 'bear', 1], ['tavşan', 'rabbit', 1], ['kaplumbağa', 'turtle', 1],
  ['yılan', 'snake', 1], ['timsah', 'crocodile', 2], ['penguen', 'penguin', 1], ['baykuş', 'owl', 2], ['kartal', 'eagle', 2],
  ['horoz', 'rooster', 2], ['fare', 'mouse', 1], ['sincap', 'squirrel', 2], ['kirpi', 'hedgehog', 2], ['televizyon', 'television', 1],
  ['bilgisayar', 'computer', 1], ['lamba', 'lamp', 1],
  { soz: 'halı', ceviri: 'carpet', zorluk: 2, serbest: ['pahalı'] },
  ['perde', 'curtain', 2], ['merdiven', 'stairs', 2],
  ['asansör', 'elevator', 2], ['çatı', 'roof', 2], ['bahçe', 'garden', 1], ['havuz', 'pool', 1], ['çadır', 'tent', 2],
  ['harita', 'map', 2], ['pusula', 'compass', 2], ['mektup', 'letter', 2], ['zarf', 'envelope', 2], ['gazete', 'newspaper', 2],
  { soz: 'sözlük', ceviri: 'dictionary', zorluk: 2, harf: ['S', 'Ö', 'Z'] },
  ['defter', 'notebook', 1], ['silgi', 'eraser', 1], ['cetvel', 'ruler', 2], ['makas', 'scissors', 1],
  ['iğne', 'needle', 2], ['düğme', 'button', 2], ['fermuar', 'zipper', 3], ['şapka', 'hat', 1],
  { soz: 'eldiven', ceviri: 'glove', zorluk: 2, gunluk: false },
  { soz: 'atkı', ceviri: 'scarf', zorluk: 2, gunluk: false },
  ['ceket', 'jacket', 2], ['pijama', 'pajamas', 2], ['terlik', 'slipper', 2], ['çorap', 'sock', 1],
  ['kemer', 'belt', 2], ['cüzdan', 'wallet', 2], ['para', 'money', 1], ['bilet', 'ticket', 2],
  { soz: 'valiz', ceviri: 'suitcase', zorluk: 2, esler: ['bavul'] },
  ['pasaport', 'passport', 2], ['otobüs', 'bus', 1], ['taksi', 'taxi', 1], ['metro', 'subway', 2], ['roket', 'rocket', 2],
  { soz: 'denizaltı', ceviri: 'submarine', zorluk: 2, kokler: ['deniz'] },
  ['helikopter', 'helicopter', 2], ['traktör', 'tractor', 2], ['ambulans', 'ambulance', 2], ['sinema', 'cinema', 2],
  ['tiyatro', 'theater', 2], ['müze', 'museum', 2], ['kütüphane', 'library', 2],
  { soz: 'eczane', ceviri: 'pharmacy', zorluk: 2, kokler: ['ecza'] },
  ['oyuncak', 'toy', 1],
  ['bebek', 'baby', 1], ['top', 'ball', 1], ['satranç', 'chess', 2], ['zar', 'dice', 2], ['bulmaca', 'puzzle', 2],
  { soz: 'kale', ceviri: 'castle', zorluk: 2, serbest: ['kalem'] },
  ['kral', 'king', 1], ['kraliçe', 'queen', 1], ['robot', 'robot', 1], ['gezegen', 'planet', 2],
  ['teleskop', 'telescope', 2], ['mıknatıs', 'magnet', 2], ['pil', 'battery', 2], ['ampul', 'light bulb', 2], ['kamera', 'camera', 2],
  ['mikrofon', 'microphone', 2],
  { soz: 'kulaklık', ceviri: 'headphones', zorluk: 2, kokler: ['kulak'] },
  ['radyo', 'radio', 2], ['davul', 'drum', 2], ['keman', 'violin', 2],
  ['zil', 'bell', 2], ['takvim', 'calendar', 2], ['doğum günü', 'birthday', 1],
  { soz: 'kardan adam', ceviri: 'snowman', zorluk: 1, gunluk: false },
  ['kahvaltı', 'breakfast', 1],
  ['çorba', 'soup', 1], ['pilav', 'rice', 1], ['makarna', 'pasta', 1], ['pizza', 'pizza', 1],
  { soz: 'simit', ceviri: 'bagel', zorluk: 1 },
  ['lokum', 'turkish delight', 2], ['bal', 'honey', 1], ['yumurta', 'egg', 1], ['süt', 'milk', 1], ['yoğurt', 'yogurt', 1],
  ['limon', 'lemon', 1], ['portakal', 'orange', 1], ['üzüm', 'grape', 1], ['armut', 'pear', 1], ['kiraz', 'cherry', 1],
  ['domates', 'tomato', 1], ['havuç', 'carrot', 1], ['patates', 'potato', 1], ['soğan', 'onion', 1], ['mısır', 'corn', 2],
  ['fındık', 'hazelnut', 2], ['ceviz', 'walnut', 2], ['kirpik', 'eyelash', 2], ['parmak', 'finger', 1], ['ayak', 'foot', 1],
  ['dirsek', 'elbow', 2], ['omuz', 'shoulder', 2], ['göbek', 'belly button', 3], ['sakal', 'beard', 2],

  // Vücut
  ['göz', 'eye', 1], ['el', 'hand', 1], ['ağız', 'mouth', 1], ['dil', 'tongue', 1], ['tırnak', 'fingernail', 1],
  ['bıyık', 'mustache', 2], ['çene', 'chin', 2], ['boyun', 'neck', 2], ['diz', 'knee', 2], ['iskelet', 'skeleton', 2],
  ['kemik', 'bone', 2], ['beyin', 'brain', 2], ['gamze', 'dimple', 3], ['parmak izi', 'fingerprint', 3], ['avuç', 'palm', 3],
  { soz: 'hapşırık', ceviri: 'sneeze', zorluk: 3, kokler: ['hapşır'] },
  { soz: 'hıçkırık', ceviri: 'hiccup', zorluk: 3, kokler: ['hıçkır'] },
  { soz: 'horultu', ceviri: 'snore', zorluk: 3, kokler: ['horla'] },

  // Doğa ve gökyüzü
  { soz: 'ay', ceviri: 'moon', zorluk: 1 },
  ['gökyüzü', 'sky', 1], ['toprak', 'soil', 1], ['çamur', 'mud', 1], ['dalga', 'wave', 1],
  ['kaya', 'rock', 1], ['yaprak', 'leaf', 1], ['ateş', 'fire', 1], ['buz', 'ice', 1], ['su', 'water', 1],
  ['dünya', 'world', 1], ['kaktüs', 'cactus', 1], ['sis', 'fog', 2], ['dolu', 'hail', 2], ['fırtına', 'storm', 2],
  ['şelale', 'waterfall', 2], ['mağara', 'cave', 2], ['tohum', 'seed', 2], ['çam', 'pine', 2], ['diken', 'thorn', 2],
  { soz: 'ayçiçeği', ceviri: 'sunflower', zorluk: 2, kokler: ['çiçek'] },
  ['duman', 'smoke', 2], ['gök gürültüsü', 'thunder', 2], ['gün batımı', 'sunset', 2], ['uzay', 'space', 2],
  ['deniz kabuğu', 'seashell', 2],
  { soz: 'inci', ceviri: 'pearl', zorluk: 2, serbest: ['birinci', 'ikinci', 'beşinci', 'altıncı', 'yedinci', 'sekizinci'] },
  ['elmas', 'diamond', 2],
  { soz: 'altın', ceviri: 'gold', zorluk: 2, gunluk: false },
  ['gölge', 'shadow', 2],
  ['kuyruklu yıldız', 'comet', 3],
  { soz: 'göktaşı', ceviri: 'meteor', zorluk: 3, kokler: ['gök', 'taş'], esler: ['meteor'] },
  ['kara delik', 'black hole', 3],
  { soz: 'uydu', ceviri: 'satellite', zorluk: 3 },
  { soz: 'tutulma', ceviri: 'eclipse', zorluk: 3, kokler: ['tutul'] },
  ['şafak', 'dawn', 3], ['vadi', 'valley', 3], ['buzul', 'glacier', 3],
  { soz: 'çığ', ceviri: 'avalanche', zorluk: 3, serbest: ['çığlık'], gunluk: false },
  { soz: 'kırağı', ceviri: 'frost', zorluk: 3, gunluk: false },
  ['girdap', 'whirlpool', 3], ['serap', 'mirage', 3], ['yankı', 'echo', 3], ['kozalak', 'pine cone', 3], ['sarmaşık', 'ivy', 3],
  ['söğüt', 'willow', 3], ['karanfil', 'carnation', 3], ['orkide', 'orchid', 3], ['uçurum', 'cliff', 3],

  // Hayvanlar
  ['at', 'horse', 1], ['eşek', 'donkey', 1], ['deve', 'camel', 1], ['kuzu', 'lamb', 1], ['kurt', 'wolf', 1],
  ['tilki', 'fox', 1], ['geyik', 'deer', 1], ['zebra', 'zebra', 1], ['ahtapot', 'octopus', 1], ['yunus', 'dolphin', 1],
  ['balina', 'whale', 1], ['köpek balığı', 'shark', 1], ['yengeç', 'crab', 1], ['kurbağa', 'frog', 1], ['sivrisinek', 'mosquito', 1],
  ['sinek', 'fly', 1], ['ördek', 'duck', 1], ['güvercin', 'pigeon', 1], ['martı', 'seagull', 1], ['gergedan', 'rhino', 2],
  ['hipopotam', 'hippo', 2], ['çita', 'cheetah', 2], ['goril', 'gorilla', 2], ['yarasa', 'bat', 2], ['lama', 'llama', 2],
  { soz: 'denizanası', ceviri: 'jellyfish', zorluk: 2, kokler: ['deniz'] },
  ['ıstakoz', 'lobster', 2], ['solucan', 'worm', 2], ['çekirge', 'grasshopper', 2], ['akrep', 'scorpion', 2],
  ['kertenkele', 'lizard', 2], ['bukalemun', 'chameleon', 2], ['leylek', 'stork', 2], ['kuğu', 'swan', 2], ['kaz', 'goose', 2],
  ['karga', 'crow', 2],
  { soz: 'devekuşu', ceviri: 'ostrich', zorluk: 2, kokler: ['deve'] },
  ['tavus kuşu', 'peacock', 2],
  { soz: 'ağaçkakan', ceviri: 'woodpecker', zorluk: 2, kokler: ['ağaç'] },
  ['hindi', 'turkey', 2],
  { soz: 'buzağı', ceviri: 'calf', zorluk: 3, esler: ['dana'] },
  ['kunduz', 'beaver', 3], ['köstebek', 'mole', 3],

  // Yerler
  ['ev', 'house', 1], ['oda', 'room', 1], ['banyo', 'bathroom', 1], ['duvar', 'wall', 1], ['park', 'park', 1],
  ['market', 'supermarket', 1], ['otel', 'hotel', 1], ['banka', 'bank', 1], ['çiftlik', 'farm', 1], ['köy', 'village', 1],
  ['sokak', 'street', 1], ['hayvanat bahçesi', 'zoo', 1], ['tünel', 'tunnel', 1], ['balkon', 'balcony', 2], ['tavan', 'ceiling', 2],
  { soz: 'havalimanı', ceviri: 'airport', zorluk: 2, kokler: ['hava', 'liman'], esler: ['havaalanı'] },
  ['istasyon', 'station', 2], ['liman', 'harbor', 2], ['akvaryum', 'aquarium', 2],
  { soz: 'trafik ışığı', ceviri: 'traffic light', zorluk: 2, esler: ['trafik lambası'], serbest: ['kişi', 'karışık'] },
  { soz: 'yaya geçidi', ceviri: 'crosswalk', zorluk: 2, serbest: ['gece'] },
  ['deniz feneri', 'lighthouse', 2], ['saray', 'palace', 2], ['kule', 'tower', 2], ['çeşme', 'fountain', 2],
  ['heykel', 'statue', 2], ['piramit', 'pyramid', 2],
  { soz: 'gökdelen', ceviri: 'skyscraper', zorluk: 2, kokler: ['gök', 'delen'] },
  ['iglo', 'igloo', 2], ['hamam', 'turkish bath', 2],
  ['kümes', 'henhouse', 2], ['garaj', 'garage', 2], ['pazar', 'bazaar', 2], ['kaldırım', 'sidewalk', 2], ['kavşak', 'intersection', 3],
  ['kulübe', 'hut', 3], ['labirent', 'maze', 3],

  // Taşıtlar
  ['motosiklet', 'motorcycle', 1], ['kamyon', 'truck', 1], ['tekerlek', 'wheel', 1], ['yol', 'road', 2], ['tramvay', 'tram', 2],
  ['teleferik', 'cable car', 2], ['vapur', 'ferry', 2],
  { soz: 'yelkenli', ceviri: 'sailboat', zorluk: 2, kokler: ['yelken'] },
  ['paraşüt', 'parachute', 2], ['itfaiye', 'fire department', 2],
  ['direksiyon', 'steering wheel', 2], ['korna', 'horn', 2], ['emniyet kemeri', 'seat belt', 2], ['zeplin', 'blimp', 3], ['uzay mekiği', 'space shuttle', 3],
  ['dümen', 'rudder', 3], ['ehliyet', 'license', 2],

  // Ev ve eşya
  ['dolap', 'cupboard', 1], ['kilit', 'lock', 1], ['çekiç', 'hammer', 1], ['süpürge', 'broom', 1], ['ütü', 'iron', 1],
  ['sabun', 'soap', 1], ['şampuan', 'shampoo', 1], ['diş fırçası', 'toothbrush', 1], ['havlu', 'towel', 1], ['tarak', 'comb', 1],
  ['duş', 'shower', 1], ['şişe', 'bottle', 1], ['kutu', 'box', 1], ['sepet', 'basket', 1], ['kumbara', 'piggy bank', 1],
  ['kibrit', 'match', 1], ['koltuk', 'armchair', 1], ['kanepe', 'sofa', 1], ['kova', 'bucket', 1], ['fırça', 'brush', 1],
  ['ip', 'rope', 1],
  { soz: 'ışık', ceviri: 'light', zorluk: 2, serbest: ['kişi', 'karışık'] },
  ['tablet', 'tablet', 1], ['raf', 'shelf', 2], ['vazo', 'vase', 2],
  ['saksı', 'flowerpot', 2], ['çerçeve', 'frame', 2], ['yorgan', 'quilt', 2], ['askı', 'hanger', 2], ['çamaşır makinesi', 'washing machine', 2],
  ['diş macunu', 'toothpaste', 2], ['küvet', 'bathtub', 2], ['musluk', 'faucet', 2], ['kumanda', 'remote', 2], ['şömine', 'fireplace', 2],
  ['baca', 'chimney', 2], ['çit', 'fence', 2], ['zincir', 'chain', 2], ['düğüm', 'knot', 2], ['çivi', 'nail', 2],
  { soz: 'tornavida', ceviri: 'screwdriver', zorluk: 2, kokler: ['vida', 'torna'] },
  { soz: 'korkuluk', ceviri: 'scarecrow', zorluk: 2, kokler: ['korku'] },
  ['yel değirmeni', 'windmill', 2], ['el feneri', 'flashlight', 2], ['posta kutusu', 'mailbox', 2],
  ['hesap makinesi', 'calculator', 2], ['çalar saat', 'alarm clock', 2], ['termometre', 'thermometer', 2], ['dürbün', 'binoculars', 2], ['büyüteç', 'magnifying glass', 2],
  ['kolye', 'necklace', 2], ['kravat', 'tie', 2], ['yelpaze', 'fan', 2],
  { soz: 'çöp kutusu', ceviri: 'trash can', zorluk: 2, esler: ['çöp kovası'] },
  { soz: 'kitaplık', ceviri: 'bookcase', zorluk: 2, kokler: ['kitap'] },
  ['uyku tulumu', 'sleeping bag', 2],
  { soz: 'kum saati', ceviri: 'hourglass', zorluk: 3, kokler: ['saat'] },
  ['pergel', 'compass', 3], ['mikroskop', 'microscope', 3], ['mercek', 'lens', 3],
  ['prizma', 'prism', 3], ['sarkaç', 'pendulum', 3], ['kaldıraç', 'lever', 3], ['makara', 'pulley', 3], ['matkap', 'drill', 3],
  ['pense', 'pliers', 3], ['tırmık', 'rake', 3], ['zımba', 'stapler', 3], ['yüksük', 'thimble', 3], ['hamak', 'hammock', 3],
  { soz: 'şezlong', ceviri: 'deck chair', zorluk: 3, gunluk: false },
  ['daktilo', 'typewriter', 3], ['plak', 'record', 3], ['çömlek', 'pottery', 3],
  { soz: 'örgü', ceviri: 'knitting', zorluk: 3 },
  ['papyon', 'bow tie', 3],

  // Giyim
  ['yüzük', 'ring', 1], ['kazak', 'sweater', 1], ['gömlek', 'shirt', 1], ['tişört', 't-shirt', 1], ['etek', 'skirt', 1],
  ['elbise', 'dress', 1], ['pantolon', 'pants', 1], ['şort', 'shorts', 1], ['mont', 'coat', 1], ['çizme', 'boots', 1],

  // İnsanlar, okul ve gündelik yaşam
  ['dede', 'grandfather', 1], ['kardeş', 'sibling', 1], ['komşu', 'neighbor', 1], ['arkadaş', 'friend', 1], ['sınıf', 'classroom', 1],
  ['öğrenci', 'student', 1], ['resim', 'picture', 1], ['şarkı', 'song', 1], ['pamuk', 'cotton', 1],
  { soz: 'yuva', ceviri: 'nest', zorluk: 1, serbest: ['yuvarlak'] },
  ['gece', 'night', 1], ['kuyruk', 'tail', 1], ['kahkaha', 'laughter', 1],
  { soz: 'piknik', ceviri: 'picnic', zorluk: 1, gunluk: false },
  { soz: 'tatil', ceviri: 'vacation', zorluk: 1 },
  ['sınav', 'exam', 2], ['karne', 'report card', 2],
  { soz: 'uyku', ceviri: 'sleep', zorluk: 2, kokler: ['uyu-'] },
  ['alkış', 'applause', 2], ['flüt', 'flute', 2],
  { soz: 'bağlama', zorluk: 2 },
  ['orkestra', 'orchestra', 2], ['konser', 'concert', 2], ['tavla', 'backgammon', 2], ['havai fişek', 'fireworks', 2],
  { soz: 'davetiye', ceviri: 'invitation', zorluk: 2, kokler: ['davet'] },
  { soz: 'kamp ateşi', ceviri: 'campfire', zorluk: 2, kokler: ['ateş'] },
  ['akordeon', 'accordion', 3], ['zurna', 'shawm', 3], ['mızıka', 'harmonica', 3],
  ['teneffüs', 'recess', 2], ['şiir', 'poem', 2], ['rüya', 'dream', 2],
  { soz: 'heyecan', ceviri: 'excitement', zorluk: 3, gunluk: false },
  { soz: 'merak', ceviri: 'curiosity', zorluk: 3, gunluk: false },
  { soz: 'sessizlik', ceviri: 'silence', zorluk: 3, kokler: ['sessiz'], gunluk: false },
  { soz: 'şans', ceviri: 'luck', zorluk: 3, gunluk: false },
  { soz: 'tembellik', ceviri: 'laziness', zorluk: 3, kokler: ['tembel'], gunluk: false },
  { soz: 'unutkanlık', ceviri: 'forgetfulness', zorluk: 3, kokler: ['unut'], gunluk: false },
  { soz: 'kıskançlık', ceviri: 'jealousy', zorluk: 3, kokler: ['kıskan'], gunluk: false },
  { soz: 'fısıltı', ceviri: 'whisper', zorluk: 3, kokler: ['fısıl'] },
]);
